import { NextResponse } from 'next/server'
import { reminderActor } from '../../../../lib/server/ravi-os-auth'
import { intelligenceAction } from '../../../../lib/server/intelligence-client'

const DOMAINS=['general','finance','career','email','tasks','journal','family','projects','health']
const RISKS=['low','medium','high','critical']
const MONTHS:Record<string,number>={january:1,february:2,march:3,april:4,may:5,june:6,july:7,august:8,september:9,october:10,november:11,december:12,jan:1,feb:2,mar:3,apr:4,jun:6,jul:7,aug:8,sep:9,sept:9,oct:10,nov:11,dec:12}
const WEEKDAYS=['sunday','monday','tuesday','wednesday','thursday','friday','saturday']
function cleanJson(text:string){return text.trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim()}
function aucklandParts(){const f=new Intl.DateTimeFormat('en-CA',{timeZone:'Pacific/Auckland',year:'numeric',month:'2-digit',day:'2-digit'});const ymd=f.format(new Date());const[y,m,d]=ymd.split('-').map(Number);return{ymd,y,m,d}}
function isoDate(y:number,m:number,d:number){return`${String(y).padStart(4,'0')}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function addDays(date:string,n:number){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function parseDate(text:string,today:string){const lower=text.toLowerCase();if(/\btoday\b/.test(lower))return today;if(/\btomorrow\b/.test(lower))return addDays(today,1);const explicit=lower.match(/\b(\d{1,2})(?:st|nd|rd|th)?\s*(?:of\s*)?(january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|jun|jul|aug|sep|sept|oct|nov|dec)(?:\s*,?\s*(20\d{2}))?\b/i);if(explicit){const day=Number(explicit[1]),month=MONTHS[explicit[2].toLowerCase()],now=aucklandParts();let year=explicit[3]?Number(explicit[3]):now.y;const candidate=isoDate(year,month,day);if(!explicit[3]&&candidate<today)year++;return isoDate(year,month,day)}const wd=lower.match(/\b(next\s+)?(sunday|monday|tuesday|wednesday|thursday|friday|saturday)\b/);if(wd){const base=new Date(`${today}T12:00:00Z`),target=WEEKDAYS.indexOf(wd[2]),current=base.getUTCDay();let delta=(target-current+7)%7;if(delta===0||wd[1])delta=delta||7;return addDays(today,delta)}return''}
function parseTime(text:string){const lower=text.toLowerCase();const explicit=lower.match(/\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)\b/);if(explicit){let h=Number(explicit[1])%12;if(explicit[3]==='pm')h+=12;return`${String(h).padStart(2,'0')}:${explicit[2]||'00'}`}const t24=lower.match(/\b([01]?\d|2[0-3]):([0-5]\d)\b/);if(t24)return`${String(Number(t24[1])).padStart(2,'0')}:${t24[2]}`;if(/\bmorning\b/.test(lower))return'09:00';if(/\bafternoon\b/.test(lower))return'15:00';if(/\bevening\b/.test(lower))return'19:00';if(/\bnight\b/.test(lower))return'20:00';return''}
function titleCase(s:string){const x=s.trim().replace(/[.]+$/,'');return x?x.charAt(0).toUpperCase()+x.slice(1):''}
function reminderTitle(text:string){const lower=text.toLowerCase();let m=text.match(/\bso\s+i\s+can\s+(.+)$/i);if(m)return titleCase(m[1]);m=text.match(/\bso\s+that\s+i\s+can\s+(.+)$/i);if(m)return titleCase(m[1]);m=text.match(/\b(?:remind me|reminder)(?:\s+for me)?(?:\s+to)?\s+(.+)$/i);let raw=m?.[1]||text;raw=raw.replace(/\b(?:on\s+)?\d{1,2}(?:st|nd|rd|th)?\s*(?:of\s*)?(?:january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|jun|jul|aug|sep|sept|oct|nov|dec)(?:\s*,?\s*20\d{2})?\b/ig,' ').replace(/\b(today|tomorrow|next\s+(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday)|monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/ig,' ').replace(/\b(morning|afternoon|evening|night)\b/ig,' ').replace(/\b\d{1,2}(?::\d{2})?\s*(?:am|pm)\b/ig,' ').replace(/\s+/g,' ').trim();raw=raw.replace(/^(?:set up|create|add)\s+(?:a\s+)?reminder(?:\s+for\s+me)?\s*/i,'').replace(/^(?:for|on|at|to)\s+/i,'');return titleCase(raw)||'Reminder'}
function deterministic(text:string,today:string){const lower=text.toLowerCase();if(/\b(remind me|reminder)\b/.test(lower)){const date=parseDate(text,today),time=parseTime(text),title=reminderTitle(text);const complete=Boolean(date&&time&&title);return{domain:'tasks',intent:'create_reminder',summary:complete?`Set reminder “${title}” for ${date} at ${time}.`:`I understood this as a reminder but need ${!date?'a date':!time?'a time':'more detail'}.`,confidence:complete?.98:.72,riskLevel:'low',requiresApproval:!complete,payload:{title,notes:'',date,time}}}return null}
async function saveAction(source:string,text:string,result:any){const saved=await intelligenceAction('record',{domain:result.domain,source,inputText:text,intent:result.intent,payload:result.payload,confidence:result.confidence,riskLevel:result.riskLevel,requiresApproval:result.requiresApproval,status:result.requiresApproval?'pending_approval':'suggested',rationale:result.summary});let actionId='';if(saved?.ok){const x=await saved.json().catch(()=>({}));actionId=String(x?.action?.id||'')}return actionId}

export async function POST(request:Request){
  if(await reminderActor()!=='ravi')return NextResponse.json({error:'Unauthorized'},{status:401})
  const body=await request.json().catch(()=>({})),text=String(body.text||'').trim();if(!text)return NextResponse.json({error:'Text required'},{status:400});const source=body.source==='voice'?'voice':'text';const today=aucklandParts().ymd
  const local=deterministic(text,today);if(local){const actionId=await saveAction(source,text,local);return NextResponse.json({...local,actionId,engine:'local'})}
  const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return NextResponse.json({domain:'general',intent:'unsupported_without_ai',summary:'This command needs advanced interpretation. Basic reminders continue to work without the AI provider.',confidence:.35,riskLevel:'low',requiresApproval:false,payload:{},engine:'local'},200)
  const system=`You are Ravi OS Intelligence Router. Understand one personal command and propose a governed action. Never silently execute. Date in Auckland: ${today}. Return ONLY JSON: {"domain":"general|finance|career|email|tasks|journal|family|projects|health","intent":"short_snake_case","summary":"one-line interpretation","confidence":0.0,"riskLevel":"low|medium|high|critical","requiresApproval":true,"payload":{}}.\nIntent conventions:\n- finance transaction: add_finance_transaction {type:"income|expense|payment|transfer|asset|liability|adjustment",amount:number|null,currency:string,category:string,merchant:string,date:"YYYY-MM-DD",notes:string}. Never invent amount.\n- note/journal/decision/idea: domain=journal intent=capture_note {title:string,content:string,type:"note|journal|decision|idea",tags:[]}.\n- task: domain=tasks intent=create_task {title:string,notes:string,dueDate:string,dueTime:string,priority:"high|medium|low",category:string}.\n- reminder: domain=tasks intent=create_reminder {title:string,notes:string,date:string,time:string}.\n- waiting on someone: domain=tasks intent=create_waiting_for {title:string,person:string,organisation:string,followUpDate:string,followUpTime:string,priority:string,channel:string}.\n- family commitment: domain=family intent=create_family_commitment {title:string,notes:string,eventDate:string,eventTime:string,category:string,assignedTo:"ravi|geet|family",priority:string}.\n- health/wellness capture: domain=health intent=health_log {date:"YYYY-MM-DD",sleepHours:number|null,steps:number|null,proteinG:number|null,waterMl:number|null,exerciseMinutes:number|null,weightKg:number|null,notes:string}. Do not infer unspoken values.\n- project/construction note: domain=projects intent=project_note {content:string,type:"note|risk|decision|action"}.\n- email: domain=email intent=email_reply {stance:"positive|negative|accept|reject|query|custom",instruction:string}. Never claim an email was sent.\n- career: domain=career intent=career_advice {question:string,focus:string}.\nGovernance: sends, replies, deletes, payments, transfers, commitments and account changes are high risk and require approval. Notes and wellness logs may be low risk but still present for review. Tasks/family commitments are medium risk and require approval. Complete personal reminders may be low risk. If ambiguous, lower confidence and preserve uncertainty instead of inventing facts.`
  try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5.6-luna',input:[{role:'system',content:[{type:'input_text',text:system}]},{role:'user',content:[{type:'input_text',text}]}],max_output_tokens:1100})});if(!r.ok)throw new Error(await r.text());const data=await r.json(),output=String(data.output_text||data.output?.flatMap((x:any)=>x.content||[]).map((x:any)=>x.text||'').join('')||''),parsed=JSON.parse(cleanJson(output)),domain=DOMAINS.includes(parsed.domain)?parsed.domain:'general',confidence=Math.max(0,Math.min(1,Number(parsed.confidence||0))),riskLevel=RISKS.includes(parsed.riskLevel)?parsed.riskLevel:'medium',result={domain,intent:String(parsed.intent||'unknown'),summary:String(parsed.summary||''),confidence,riskLevel,requiresApproval:parsed.requiresApproval!==false,payload:parsed.payload&&typeof parsed.payload==='object'?parsed.payload:{}};const actionId=await saveAction(source,text,result);return NextResponse.json({...result,actionId,engine:'openai'})}catch{const fallback=deterministic(text,today);if(fallback){const actionId=await saveAction(source,text,fallback);return NextResponse.json({...fallback,actionId,engine:'local-fallback'})}return NextResponse.json({error:'Unable to interpret that command right now'},{status:500})}
}
