'use client'

import Link from 'next/link'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, BookOpenText, Check, Clock3, Edit3, Pause, Play, Plus, Repeat2, Save, Trash2, X } from 'lucide-react'
import styles from './journal.module.css'

type Entry={id:string;entryType:'note'|'journal'|'decision'|'idea';title:string;body:string;tags:string[];mood:string;occurredOn:string;createdAt:string}
type Obligation={id:string;title:string;notes:string;category:string;cadence:'once'|'weekly'|'monthly'|'quarterly'|'yearly'|'custom';cadenceDays?:number|null;nextDueDate:string;priority:'high'|'medium'|'low';status:'active'|'paused'|'completed'|'cancelled';lastCompletedAt?:string|null}
type Tab='journal'|'obligations'

function todayNZ(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Pacific/Auckland',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function prettyDate(d:string){return new Date(`${d}T12:00:00`).toLocaleDateString('en-NZ',{weekday:'short',day:'numeric',month:'short',year:'numeric'})}
function dueState(d:string){const today=todayNZ();if(d<today)return'overdue';if(d===today)return'today';return'future'}

export default function JournalPage(){
 const[tab,setTab]=useState<Tab>('journal');const[entries,setEntries]=useState<Entry[]>([]);const[obligations,setObligations]=useState<Obligation[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('')
 const[entryOpen,setEntryOpen]=useState(false);const[entryId,setEntryId]=useState<string|null>(null);const[entryType,setEntryType]=useState<Entry['entryType']>('note');const[entryTitle,setEntryTitle]=useState('');const[entryBody,setEntryBody]=useState('');const[entryTags,setEntryTags]=useState('');const[entryDate,setEntryDate]=useState(todayNZ())
 const[obOpen,setObOpen]=useState(false);const[obId,setObId]=useState<string|null>(null);const[obTitle,setObTitle]=useState('');const[obNotes,setObNotes]=useState('');const[obCategory,setObCategory]=useState('Personal');const[obCadence,setObCadence]=useState<Obligation['cadence']>('monthly');const[obDays,setObDays]=useState('30');const[obDate,setObDate]=useState(todayNZ());const[obPriority,setObPriority]=useState<Obligation['priority']>('medium');const[working,setWorking]=useState(false)
 const load=async()=>{try{const r=await fetch('/api/journal',{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();setEntries(d.entries||[]);setObligations(d.obligations||[]);setError('')}catch{setError('Journal could not be loaded.')}finally{setLoading(false)}}
 useEffect(()=>{load();if(new URLSearchParams(location.search).get('new')==='1')setEntryOpen(true)},[])
 const activeObligations=useMemo(()=>obligations.filter(o=>o.status!=='completed'&&o.status!=='cancelled'),[obligations])
 const resetEntry=()=>{setEntryId(null);setEntryType('note');setEntryTitle('');setEntryBody('');setEntryTags('');setEntryDate(todayNZ())}
 const resetOb=()=>{setObId(null);setObTitle('');setObNotes('');setObCategory('Personal');setObCadence('monthly');setObDays('30');setObDate(todayNZ());setObPriority('medium')}
 async function send(action:string,payload:Record<string,unknown>){const r=await fetch('/api/journal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});if(!r.ok)throw new Error();return r.json()}
 async function saveEntry(e:FormEvent){e.preventDefault();if(!entryBody.trim())return;setWorking(true);try{await send(entryId?'entry_update':'entry_create',{id:entryId,entryType,title:entryTitle.trim(),body:entryBody.trim(),tags:entryTags.split(',').map(x=>x.trim()).filter(Boolean),occurredOn:entryDate});await load();setEntryOpen(false);resetEntry()}catch{setError('Entry could not be saved.')}finally{setWorking(false)}}
 async function saveOb(e:FormEvent){e.preventDefault();if(!obTitle.trim()||!obDate)return;setWorking(true);try{await send(obId?'obligation_update':'obligation_create',{id:obId,title:obTitle.trim(),notes:obNotes.trim(),category:obCategory.trim()||'Personal',cadence:obCadence,cadenceDays:obCadence==='custom'?Number(obDays):null,nextDueDate:obDate,priority:obPriority,status:'active'});await load();setObOpen(false);resetOb()}catch{setError('Obligation could not be saved.')}finally{setWorking(false)}}
 const editEntry=(x:Entry)=>{setEntryId(x.id);setEntryType(x.entryType);setEntryTitle(x.title);setEntryBody(x.body);setEntryTags(x.tags.join(', '));setEntryDate(x.occurredOn);setEntryOpen(true)}
 const editOb=(x:Obligation)=>{setObId(x.id);setObTitle(x.title);setObNotes(x.notes);setObCategory(x.category);setObCadence(x.cadence);setObDays(String(x.cadenceDays||30));setObDate(x.nextDueDate);setObPriority(x.priority);setObOpen(true)}
 const remove=async(action:string,id:string)=>{if(!confirm('Delete this item?'))return;try{await send(action,{id});await load()}catch{setError('Could not delete item.')}}
 const complete=async(id:string)=>{try{await send('obligation_complete',{id});await load()}catch{setError('Could not complete obligation.')}}
 const pause=async(x:Obligation)=>{try{await send('obligation_pause',{id:x.id,paused:x.status!=='paused'});await load()}catch{setError('Could not update obligation.')}}

 return <main className={styles.shell}>
  <header className={styles.header}><Link href='/' className={styles.back}><ArrowLeft/>Ravi OS</Link><div><p>JOURNAL & OBLIGATIONS</p><h1>Your private memory.</h1><span>Notes, decisions and recurring responsibilities that should not disappear in browser storage.</span></div></header>
  <section className={styles.switcher}><button className={tab==='journal'?styles.active:''} onClick={()=>setTab('journal')}><BookOpenText/>Journal <b>{entries.length}</b></button><button className={tab==='obligations'?styles.active:''} onClick={()=>setTab('obligations')}><Repeat2/>Recurring <b>{activeObligations.length}</b></button></section>
  {error&&<div className={styles.error}>{error}</div>}

  {tab==='journal'&&<><section className={styles.toolbar}><div><p>PRIVATE JOURNAL</p><h2>Capture what matters</h2></div><button onClick={()=>{resetEntry();setEntryOpen(true)}}><Plus/>New entry</button></section>
  {entryOpen&&<section className={styles.formCard}><div className={styles.formHead}><div><p>{entryId?'EDIT ENTRY':'NEW ENTRY'}</p><h2>{entryId?'Update entry':'Add to your journal'}</h2></div><button onClick={()=>{setEntryOpen(false);resetEntry()}}><X/></button></div><form onSubmit={saveEntry}><div className={styles.two}><label>Type<select value={entryType} onChange={e=>setEntryType(e.target.value as Entry['entryType'])}><option value='note'>Note</option><option value='journal'>Journal</option><option value='decision'>Decision</option><option value='idea'>Idea</option></select></label><label>Date<input type='date' value={entryDate} onChange={e=>setEntryDate(e.target.value)}/></label></div><label>Title <span>optional</span><input value={entryTitle} onChange={e=>setEntryTitle(e.target.value)} placeholder='Short heading'/></label><label>Entry<textarea autoFocus value={entryBody} onChange={e=>setEntryBody(e.target.value)} placeholder='Write what you want Ravi OS to remember.'/></label><label>Tags <span>comma separated</span><input value={entryTags} onChange={e=>setEntryTags(e.target.value)} placeholder='family, construction, idea'/></label><button className={styles.save} disabled={working||!entryBody.trim()}><Save/>{working?'Saving…':'Save entry'}</button></form></section>}
  <section className={styles.listCard}>{loading?<div className={styles.empty}>Loading journal…</div>:entries.length===0?<div className={styles.empty}><BookOpenText/><b>No journal entries yet</b><span>Use this for notes, ideas, decisions and personal context you want to keep.</span></div>:<div className={styles.entryList}>{entries.map(x=><article className={styles.entry} key={x.id}><div className={styles.entryTop}><span className={styles.type}>{x.entryType}</span><small>{prettyDate(x.occurredOn)}</small></div>{x.title&&<h3>{x.title}</h3>}<p>{x.body}</p>{x.tags.length>0&&<div className={styles.tags}>{x.tags.map(t=><span key={t}>#{t}</span>)}</div>}<div className={styles.actions}><button onClick={()=>editEntry(x)}><Edit3/>Edit</button><button onClick={()=>remove('entry_delete',x.id)}><Trash2/>Delete</button></div></article>)}</div>}</section></>}

  {tab==='obligations'&&<><section className={styles.toolbar}><div><p>RECURRING OBLIGATIONS</p><h2>Things that come back</h2></div><button onClick={()=>{resetOb();setObOpen(true)}}><Plus/>Add obligation</button></section>
  {obOpen&&<section className={styles.formCard}><div className={styles.formHead}><div><p>{obId?'EDIT OBLIGATION':'NEW OBLIGATION'}</p><h2>{obId?'Update obligation':'Track a recurring responsibility'}</h2></div><button onClick={()=>{setObOpen(false);resetOb()}}><X/></button></div><form onSubmit={saveOb}><label>Title<input autoFocus value={obTitle} onChange={e=>setObTitle(e.target.value)} placeholder='e.g. Renew car registration'/></label><label>Notes<textarea value={obNotes} onChange={e=>setObNotes(e.target.value)} placeholder='Reference numbers, instructions or context'/></label><div className={styles.two}><label>Category<input value={obCategory} onChange={e=>setObCategory(e.target.value)}/></label><label>Priority<select value={obPriority} onChange={e=>setObPriority(e.target.value as Obligation['priority'])}><option value='high'>High</option><option value='medium'>Medium</option><option value='low'>Low</option></select></label></div><div className={styles.two}><label>Cadence<select value={obCadence} onChange={e=>setObCadence(e.target.value as Obligation['cadence'])}><option value='once'>One-off</option><option value='weekly'>Weekly</option><option value='monthly'>Monthly</option><option value='quarterly'>Quarterly</option><option value='yearly'>Yearly</option><option value='custom'>Custom days</option></select></label><label>Next due<input type='date' value={obDate} onChange={e=>setObDate(e.target.value)}/></label></div>{obCadence==='custom'&&<label>Repeat every days<input type='number' min='1' value={obDays} onChange={e=>setObDays(e.target.value)}/></label>}<button className={styles.save} disabled={working||!obTitle.trim()||!obDate}><Save/>{working?'Saving…':'Save obligation'}</button></form></section>}
  <section className={styles.listCard}>{loading?<div className={styles.empty}>Loading obligations…</div>:obligations.length===0?<div className={styles.empty}><Repeat2/><b>No recurring obligations yet</b><span>Add renewals, bills, subscriptions, reviews or duties you do not want to forget.</span></div>:<div className={styles.obList}>{obligations.map(x=><article className={`${styles.obligation} ${styles[dueState(x.nextDueDate)]}`} key={x.id}><div className={styles.obMain}><div className={styles.obTitle}><b>{x.title}</b><em className={styles[x.priority]}>{x.priority}</em></div><small>{x.category} · {x.cadence==='custom'?`Every ${x.cadenceDays} days`:x.cadence}</small>{x.notes&&<p>{x.notes}</p>}<span><Clock3/>{x.status==='completed'?'Completed':x.status==='paused'?'Paused':`${dueState(x.nextDueDate)==='overdue'?'Overdue':'Due'} ${prettyDate(x.nextDueDate)}`}</span></div><div className={styles.obActions}>{x.status!=='completed'&&<button onClick={()=>complete(x.id)}><Check/>Done</button>}{x.status!=='completed'&&<button onClick={()=>pause(x)}>{x.status==='paused'?<Play/>:<Pause/>}{x.status==='paused'?'Resume':'Pause'}</button>}<button onClick={()=>editOb(x)}><Edit3/>Edit</button><button onClick={()=>remove('obligation_delete',x.id)}><Trash2/>Delete</button></div></article>)}</div>}</section></>}
  <nav className={styles.bottom}><Link href='/'>Home</Link><Link href='/tasks'>Tasks</Link><button onClick={()=>{setTab('journal');resetEntry();setEntryOpen(true)}}><Plus/></button><Link href='/calendar'>Calendar</Link></nav>
 </main>
}
