'use client'

import Link from 'next/link'
import { useEffect,useState } from 'react'
import { ArrowLeft,Play,RefreshCw,ShieldCheck,Zap } from 'lucide-react'
import s from '../intelligence.module.css'

type Rule={id:string;name:string;domain:string;trigger_type:string;action_type:string;risk_level:string;requires_approval:boolean;enabled:boolean}
type Run={id:string;domain:string;status:string;risk_level:string;outcome:string;created_at:string}
export default function AutomationPage(){const[rules,setRules]=useState<Rule[]>([]);const[runs,setRuns]=useState<Run[]>([]);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('')
 const load=async()=>{const r=await fetch('/api/automation',{cache:'no-store'});if(r.ok){const d=await r.json();setRules(d.rules||[]);setRuns(d.runs||[])}}
 useEffect(()=>{load()},[])
 async function toggle(rule:Rule){await fetch('/api/automation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'toggle',id:rule.id,enabled:!rule.enabled})});load()}
 async function evaluate(){setBusy(true);setMsg('Checking active rules against current Ravi OS data…');const r=await fetch('/api/automation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'evaluate'})});const d=await r.json().catch(()=>({}));setMsg(r.ok?`${d.runs?.length||0} new action${d.runs?.length===1?'':'s'} generated. Existing recent matches were not duplicated.`:d.error||'Evaluation failed');setBusy(false);load()}
 return <main className={s.shell}><header className={s.header}><Link className={s.back} href='/'><ArrowLeft/>Ravi OS</Link><div className={s.heading}><p className={s.eyebrow}>AUTOMATION CONTROL CENTRE</p><h1>Automate work. Keep control.</h1><span>Rules detect conditions, prepare the next action, apply risk controls and preserve an audit trail.</span></div><span className={s.private}><ShieldCheck/>Ravi only</span></header><section className={s.hero}><p>GOVERNED AUTOMATION</p><h2>Trigger → understand → propose → approve → execute → audit.</h2><span>Low-risk alerts can surface automatically. Consequential actions stay behind human approval.</span><div className={s.heroActions}><button onClick={evaluate} disabled={busy}><Play/>{busy?'Evaluating…':'Evaluate now'}</button><Link href='/'><RefreshCw/>Executive Home</Link></div></section>{msg&&<p className={s.statusLine}>{msg}</p>}<div className={s.grid}><section className={`${s.card} ${s.wide}`}><div className={s.cardHead}><div><p>ACTIVE RULES</p><h2>{rules.filter(x=>x.enabled).length} enabled · {rules.length} configured</h2></div><Zap/></div><div>{rules.map(r=><div className={s.rule} key={r.id}><div><b>{r.name}</b><small>{r.domain} · {r.trigger_type} → {r.action_type} · {r.risk_level} risk · {r.requires_approval?'approval required':'safe to surface'}</small></div><button className={`${s.switch} ${r.enabled?s.on:''}`} onClick={()=>toggle(r)} aria-label={`Toggle ${r.name}`}><i/></button></div>)}</div></section><section className={`${s.card} ${s.wide}`}><div className={s.cardHead}><div><p>DECISION QUEUE</p><h2>Automation outcomes</h2></div></div>{runs.length===0?<div className={s.empty}><b>No automation actions yet</b><span>Run an evaluation. Ravi OS will create actions only when a configured condition is true.</span></div>:<div className={s.list}>{runs.map(r=><div className={s.item} key={r.id}><span className={s.itemIcon}><Zap/></span><div className={s.itemBody}><b>{r.outcome||r.domain}</b><small>{r.domain} · {r.status} · {new Date(r.created_at).toLocaleString('en-NZ')}</small></div><span className={`${s.badge} ${s[r.risk_level]||''}`}>{r.risk_level}</span></div>)}</div>}</section></div></main>}
