import { randomBytes } from 'crypto'
import { calendarVaultAction } from './calendar-vault-client'

const APP_URL=process.env.NEXT_PUBLIC_APP_URL||'https://my.ravigupta.dev'
const CLIENT_ID=process.env.GOOGLE_CLIENT_ID||''
const CLIENT_SECRET=process.env.GOOGLE_CLIENT_SECRET||''
const REDIRECT_URI=`${APP_URL}/api/google/callback`
const SCOPES=['openid','email','https://www.googleapis.com/auth/calendar.events','https://www.googleapis.com/auth/gmail.modify']

type Connection={access_token:string;refresh_token?:string|null;expires_at?:string|null;provider_email?:string|null;calendar_id?:string|null}
export function googleSuiteConfigured(){return Boolean(CLIENT_ID&&CLIENT_SECRET)}
export function newGoogleSuiteState(){return randomBytes(24).toString('hex')}
export function googleSuiteAuthUrl(state:string){const p=new URLSearchParams({client_id:CLIENT_ID,redirect_uri:REDIRECT_URI,response_type:'code',access_type:'offline',prompt:'consent',include_granted_scopes:'true',scope:SCOPES.join(' '),state});return`https://accounts.google.com/o/oauth2/v2/auth?${p.toString()}`}
export async function exchangeGoogleSuiteCode(code:string){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:CLIENT_ID,client_secret:CLIENT_SECRET,redirect_uri:REDIRECT_URI,grant_type:'authorization_code'}),cache:'no-store'});if(!r.ok)throw new Error(`Google token exchange failed (${r.status})`);return r.json() as Promise<{access_token:string;refresh_token?:string;expires_in?:number;scope?:string;token_type?:string}>}
async function refresh(refreshToken:string){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({refresh_token:refreshToken,client_id:CLIENT_ID,client_secret:CLIENT_SECRET,grant_type:'refresh_token'}),cache:'no-store'});if(!r.ok)throw new Error(`Google token refresh failed (${r.status})`);return r.json() as Promise<{access_token:string;expires_in?:number;scope?:string;token_type?:string}>}
export async function googleSuiteEmail(accessToken:string){const r=await fetch('https://www.googleapis.com/oauth2/v2/userinfo',{headers:{Authorization:`Bearer ${accessToken}`},cache:'no-store'});if(!r.ok)return null;const d=await r.json().catch(()=>({}));return typeof d?.email==='string'?d.email:null}
async function connection(){const r=await calendarVaultAction('get');if(!r?.ok)throw new Error('Google account is not connected');const d=await r.json();return d.connection as Connection}
async function store(c:Connection,extra:Record<string,unknown>={}){const r=await calendarVaultAction('store',{accessToken:c.access_token,refreshToken:c.refresh_token||undefined,expiresAt:c.expires_at||undefined,calendarId:c.calendar_id||'primary',email:c.provider_email||undefined,...extra});if(!r?.ok)throw new Error('Unable to save Google connection')}
export async function validGoogleSuiteToken(){const c=await connection(),exp=c.expires_at?new Date(c.expires_at).getTime():0;if(c.access_token&&exp>Date.now()+60000)return c.access_token;if(!c.refresh_token)throw new Error('Google account needs to be reconnected');const fresh=await refresh(c.refresh_token),expiresAt=new Date(Date.now()+(fresh.expires_in||3600)*1000).toISOString();await store(c,{accessToken:fresh.access_token,refreshToken:c.refresh_token,expiresAt,scope:fresh.scope,tokenType:fresh.token_type});return fresh.access_token}
async function gmail(path:string,init:RequestInit={}){const token=await validGoogleSuiteToken();return fetch(`https://gmail.googleapis.com/gmail/v1/users/me${path}`,{...init,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(init.headers||{})},cache:'no-store'})}
function header(headers:any[],name:string){return String(headers?.find((x:any)=>String(x.name).toLowerCase()===name.toLowerCase())?.value||'')}
export async function listRecentGmail(max=40){const q=encodeURIComponent('newer_than:14d -category:promotions -in:spam -in:trash');const list=await gmail(`/messages?maxResults=${Math.min(max,60)}&q=${q}`);if(!list.ok)throw new Error(`Gmail list failed (${list.status})`);const ids=(await list.json()).messages||[];const rows=await Promise.all(ids.map(async(x:any)=>{const r=await gmail(`/messages/${encodeURIComponent(x.id)}?format=metadata&metadataHeaders=Subject&metadataHeaders=From&metadataHeaders=Date`);if(!r.ok)return null;const d=await r.json();const h=d.payload?.headers||[];return{id:String(d.id),threadId:String(d.threadId||''),subject:header(h,'Subject'),from:header(h,'From'),date:header(h,'Date'),snippet:String(d.snippet||''),labelIds:d.labelIds||[]}}));return rows.filter(Boolean)}
function b64url(text:string){return Buffer.from(text,'utf8').toString('base64').replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
export async function createGmailReplyDraft(threadId:string,to:string,subject:string,body:string){const raw=b64url(`To: ${to}\r\nSubject: ${subject.startsWith('Re:')?subject:`Re: ${subject}`}\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n${body}`);const payload:any={message:{raw}};if(threadId)payload.message.threadId=threadId;const r=await gmail('/drafts',{method:'POST',body:JSON.stringify(payload)});if(!r.ok)throw new Error(`Gmail draft failed (${r.status})`);return r.json()}
export async function sendGmailDraft(draftId:string){const r=await gmail('/drafts/send',{method:'POST',body:JSON.stringify({id:draftId})});if(!r.ok)throw new Error(`Gmail send failed (${r.status})`);return r.json()}
