'use client'

import Link from 'next/link'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Banknote, BrainCircuit, Building2, CircleDollarSign, CreditCard, Landmark, Mic, MicOff, Plus, RefreshCw, ShieldCheck, Sparkles, Trash2, WalletCards } from 'lucide-react'
import styles from './finance.module.css'

type Account={id:string;name:string;type:string;institution:string;currency:string;openingBalance:number;includeInNetWorth:boolean;active:boolean;notes:string}
type Tx={id:string;accountId:string;transferAccountId:string;type:string;amount:number;currency:string;baseAmountNzd:number|null;fxRateToNzd:number|null;category:string;merchant:string;date:string;notes:string;source:string;status:string;confidence:number;riskLevel:string;createdAt:string}
type Advice={headline:string;health:'good'|'watch'|'attention';observations:string[];actions:{title:string;why:string;priority:string}[];controls:string[];questions:string[]}

type Draft={type:string;amount:string;currency:string;category:string;merchant:string;date:string;notes:string;accountId:string;baseAmountNzd:string;source:'manual'|'voice'}
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Pacific/Auckland',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const emptyDraft=():Draft=>({type:'expense',amount:'',currency:'NZD',category:'Other',merchant:'',date:today(),notes:'',accountId:'',baseAmountNzd:'',source:'manual'})
const money=(n:number,c='NZD')=>new Intl.NumberFormat('en-NZ',{style:'currency',currency:c,maximumFractionDigits:2}).format(n||0)

export default function FinancePage(){
  const[accounts,setAccounts]=useState<Account[]>([]);const[transactions,setTransactions]=useState<Tx[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('')
  const[tab,setTab]=useState<'overview'|'ledger'|'accounts'>('overview');const[formOpen,setFormOpen]=useState(false);const[draft,setDraft]=useState<Draft>(emptyDraft());const[saving,setSaving]=useState(false)
  const[accountOpen,setAccountOpen]=useState(false);const[accountName,setAccountName]=useState('');const[accountType,setAccountType]=useState('bank');const[accountCurrency,setAccountCurrency]=useState('NZD');const[institution,setInstitution]=useState('')
  const[listening,setListening]=useState(false);const[voiceText,setVoiceText]=useState('');const[voiceMessage,setVoiceMessage]=useState('');const[advice,setAdvice]=useState<Advice|null>(null);const[reviewing,setReviewing]=useState(false)

  const load=async()=>{setLoading(true);try{const r=await fetch('/api/finance',{cache:'no-store'});if(!r.ok)throw new Error('Finance data could not be loaded');const d=await r.json();setAccounts(d.accounts||[]);setTransactions(d.transactions||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'Finance data could not be loaded')}finally{setLoading(false)}}
  useEffect(()=>{load()},[])

  const currentMonth=new Intl.DateTimeFormat('en-CA',{timeZone:'Pacific/Auckland',year:'numeric',month:'2-digit'}).format(new Date())
  const metrics=useMemo(()=>{const rows=transactions.filter(t=>t.status!=='void'&&t.date.startsWith(currentMonth));const nzd=(t:Tx)=>t.baseAmountNzd??(t.currency==='NZD'?t.amount:0);const income=rows.filter(t=>t.type==='income').reduce((a,t)=>a+nzd(t),0);const expense=rows.filter(t=>t.type==='expense'||t.type==='payment').reduce((a,t)=>a+nzd(t),0);const missingFx=rows.filter(t=>t.currency!=='NZD'&&t.baseAmountNzd==null).length;return{income,expense,net:income-expense,count:rows.length,missingFx}},[transactions,currentMonth])
  const categories=useMemo(()=>{const m=new Map<string,number>();for(const t of transactions.filter(t=>t.date.startsWith(currentMonth)&&(t.type==='expense'||t.type==='payment'))){const v=t.baseAmountNzd??(t.currency==='NZD'?t.amount:0);m.set(t.category,(m.get(t.category)||0)+v)}return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6)},[transactions,currentMonth])

  async function saveTx(e:FormEvent){e.preventDefault();const amount=Number(draft.amount);if(!(amount>=0))return;setSaving(true);try{const body:any={kind:'transaction',type:draft.type,amount,currency:draft.currency.toUpperCase(),category:draft.category||'Other',merchant:draft.merchant,date:draft.date,notes:draft.notes,accountId:draft.accountId||undefined,source:draft.source,confidence:draft.source==='voice'?0.85:1,riskLevel:'low'};if(draft.currency==='NZD')body.baseAmountNzd=amount;else if(draft.baseAmountNzd)body.baseAmountNzd=Number(draft.baseAmountNzd);const r=await fetch('/api/finance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error('Could not save transaction');setDraft(emptyDraft());setFormOpen(false);await load()}catch(e){setVoiceMessage(e instanceof Error?e.message:'Could not save transaction')}finally{setSaving(false)}}
  async function addAccount(e:FormEvent){e.preventDefault();if(!accountName.trim())return;setSaving(true);try{const r=await fetch('/api/finance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'account',name:accountName.trim(),type:accountType,currency:accountCurrency.toUpperCase(),institution})});if(!r.ok)throw new Error('Could not add account');setAccountName('');setInstitution('');setAccountOpen(false);await load()}finally{setSaving(false)}}
  async function removeTx(id:string){if(!confirm('Remove this transaction from the active ledger?'))return;const r=await fetch(`/api/finance/transactions/${id}`,{method:'DELETE'});if(r.ok)await load()}

  async function interpret(text:string){setVoiceMessage('Understanding…');try{const r=await fetch('/api/intelligence/interpret',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,source:'voice'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not understand that');if(d.domain==='finance'&&d.intent==='add_finance_transaction'){const p=d.payload||{};setDraft({type:p.type||'expense',amount:p.amount==null?'':String(p.amount),currency:p.currency||'NZD',category:p.category||'Other',merchant:p.merchant||'',date:p.date||today(),notes:p.notes||'',accountId:'',baseAmountNzd:'',source:'voice'});setFormOpen(true);setVoiceMessage(`${Math.round((d.confidence||0)*100)}% confident. Review before saving.`)}else setVoiceMessage(d.summary||'I understood the command, but it belongs in another Ravi OS area.')}catch(e){setVoiceMessage(e instanceof Error?e.message:'Voice interpretation failed')}}
  function startVoice(){const W=window as any;const SR=W.SpeechRecognition||W.webkitSpeechRecognition;if(!SR){setVoiceMessage('Speech recognition is not available in this browser. Type the transaction instead.');return}const r=new SR();r.lang='en-NZ';r.interimResults=false;r.continuous=false;r.onstart=()=>{setListening(true);setVoiceMessage('Listening…')};r.onend=()=>setListening(false);r.onerror=()=>{setListening(false);setVoiceMessage('I could not hear that clearly. Try again.')};r.onresult=(e:any)=>{const text=String(e.results?.[0]?.[0]?.transcript||'').trim();setVoiceText(text);if(text)interpret(text)};r.start()}
  async function review(){setReviewing(true);try{const r=await fetch('/api/finance/advice',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Review unavailable');setAdvice(d.advice)}catch(e){setVoiceMessage(e instanceof Error?e.message:'Review unavailable')}finally{setReviewing(false)}}

  return <main className={styles.shell}>
    <header className={styles.header}><Link href='/'><ArrowLeft/>Ravi OS</Link><div><p>FINANCE CONTROL CENTRE</p><h1>Know where the money is going.</h1><span>Records, controls, calculations and governed financial intelligence.</span></div><span className={styles.private}><ShieldCheck/>Ravi only</span></header>

    <section className={styles.voice}><button className={listening?styles.listening:''} onClick={startVoice}>{listening?<MicOff/>:<Mic/>}<span><b>{listening?'Listening…':'Speak a transaction'}</b><small>“Spent 46 dollars on groceries at Countdown today.”</small></span></button><div><Sparkles/><span><b>Ravi Finance Intelligence</b><small>{voiceMessage||'Voice entries are interpreted first. Nothing financial is posted without your review.'}</small>{voiceText&&<em>“{voiceText}”</em>}</span></div></section>

    <section className={styles.metrics}><div><CircleDollarSign/><span><small>THIS MONTH INCOME</small><b>{money(metrics.income)}</b></span></div><div><CreditCard/><span><small>THIS MONTH SPEND</small><b>{money(metrics.expense)}</b></span></div><div className={metrics.net<0?styles.negative:''}><Banknote/><span><small>NET CASH FLOW</small><b>{money(metrics.net)}</b></span></div><div><RefreshCw/><span><small>RECORD QUALITY</small><b>{metrics.missingFx?`${metrics.missingFx} FX gap${metrics.missingFx>1?'s':''}`:'Ready'}</b></span></div></section>

    <nav className={styles.tabs}><button className={tab==='overview'?styles.active:''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='ledger'?styles.active:''} onClick={()=>setTab('ledger')}>Ledger</button><button className={tab==='accounts'?styles.active:''} onClick={()=>setTab('accounts')}>Accounts</button></nav>

    {error&&<div className={styles.error}>{error}</div>}
    {tab==='overview'&&<div className={styles.grid}>
      <section className={styles.card}><div className={styles.cardHead}><div><p>CONTROLLER</p><h2>Intelligent review</h2></div><button onClick={review} disabled={reviewing}><BrainCircuit/>{reviewing?'Reviewing…':'Review finances'}</button></div>{!advice?<div className={styles.empty}><BrainCircuit/><b>Run a finance review</b><span>Ravi OS will analyse bookkeeping quality, cash flow, controls and next actions from your actual ledger.</span></div>:<div className={styles.advice}><div className={`${styles.health} ${styles[advice.health]}`}>{advice.health.toUpperCase()}</div><h3>{advice.headline}</h3>{advice.observations?.map((x,i)=><p key={i}>{x}</p>)}<h4>Recommended actions</h4>{advice.actions?.map((x,i)=><div className={styles.action} key={i}><b>{x.title}</b><span>{x.why}</span><em>{x.priority}</em></div>)}</div>}</section>
      <section className={styles.card}><div className={styles.cardHead}><div><p>SPENDING</p><h2>Top categories this month</h2></div><WalletCards/></div>{categories.length===0?<div className={styles.empty}><WalletCards/><b>No spending recorded</b><span>Add transactions manually or by voice.</span></div>:<div className={styles.categories}>{categories.map(([name,value])=><div key={name}><span><b>{name}</b><small>{money(value)}</small></span><i style={{width:`${Math.max(6,(value/(categories[0]?.[1]||1))*100)}%`}}/></div>)}</div>}</section>
      <section className={styles.card}><div className={styles.cardHead}><div><p>CONTROL RULES</p><h2>What Ravi OS checks</h2></div><ShieldCheck/></div><div className={styles.controls}><span>✓ Foreign-currency entries without NZD conversion</span><span>✓ Monthly income vs spend and negative cash flow</span><span>✓ Uncategorized / low-confidence entries</span><span>✓ Review-before-post for AI and voice capture</span><span>✓ High-risk financial actions require approval</span></div></section>
    </div>}

    {tab==='ledger'&&<section className={styles.card}><div className={styles.cardHead}><div><p>LEDGER</p><h2>Transactions</h2></div><button onClick={()=>{setDraft(emptyDraft());setFormOpen(v=>!v)}}><Plus/>Add</button></div>{formOpen&&<form className={styles.form} onSubmit={saveTx}><div className={styles.row3}><label>Type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}><option value='expense'>Expense</option><option value='income'>Income</option><option value='payment'>Payment</option><option value='transfer'>Transfer</option><option value='asset'>Asset</option><option value='liability'>Liability</option><option value='adjustment'>Adjustment</option></select></label><label>Amount<input type='number' step='0.01' value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})}/></label><label>Currency<input value={draft.currency} maxLength={3} onChange={e=>setDraft({...draft,currency:e.target.value.toUpperCase()})}/></label></div>{draft.currency!=='NZD'&&<label>NZD value for reporting<input type='number' step='0.01' value={draft.baseAmountNzd} onChange={e=>setDraft({...draft,baseAmountNzd:e.target.value})} placeholder='Enter converted NZD amount'/></label>}<div className={styles.row2}><label>Category<input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label><label>Merchant / payee<input value={draft.merchant} onChange={e=>setDraft({...draft,merchant:e.target.value})}/></label></div><div className={styles.row2}><label>Date<input type='date' value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Account<select value={draft.accountId} onChange={e=>setDraft({...draft,accountId:e.target.value})}><option value=''>Not assigned</option>{accounts.filter(a=>a.active).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div><label>Notes<textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><button className={styles.primary} disabled={saving||!draft.amount}>{saving?'Saving…':'Review complete · Post transaction'}</button></form>}{loading?<div className={styles.empty}>Loading…</div>:transactions.length===0?<div className={styles.empty}><CreditCard/><b>No transactions yet</b><span>Start with an expense, income, payment or voice entry.</span></div>:<div className={styles.ledger}>{transactions.map(t=><article key={t.id}><span className={`${styles.txIcon} ${styles[t.type]||''}`}>{t.type==='income'?'+':'−'}</span><div><b>{t.merchant||t.category}</b><small>{t.category} · {t.date} · {t.source}</small>{t.notes&&<p>{t.notes}</p>}</div><strong>{t.type==='income'?'+':'−'}{money(t.amount,t.currency)}</strong><button aria-label='Remove' onClick={()=>removeTx(t.id)}><Trash2/></button></article>)}</div>}</section>}

    {tab==='accounts'&&<section className={styles.card}><div className={styles.cardHead}><div><p>ACCOUNTS</p><h2>Banks, cards, cash and assets</h2></div><button onClick={()=>setAccountOpen(v=>!v)}><Plus/>Account</button></div>{accountOpen&&<form className={styles.form} onSubmit={addAccount}><div className={styles.row2}><label>Account name<input value={accountName} onChange={e=>setAccountName(e.target.value)} placeholder='e.g. ANZ Everyday'/></label><label>Type<select value={accountType} onChange={e=>setAccountType(e.target.value)}><option value='bank'>Bank</option><option value='cash'>Cash</option><option value='credit_card'>Credit card</option><option value='fixed_deposit'>Fixed deposit</option><option value='investment'>Investment</option><option value='asset'>Asset</option><option value='liability'>Liability</option><option value='other'>Other</option></select></label></div><div className={styles.row2}><label>Institution<input value={institution} onChange={e=>setInstitution(e.target.value)}/></label><label>Currency<input value={accountCurrency} maxLength={3} onChange={e=>setAccountCurrency(e.target.value.toUpperCase())}/></label></div><button className={styles.primary} disabled={saving||!accountName.trim()}>Add account</button></form>}<div className={styles.accounts}>{accounts.length===0?<div className={styles.empty}><Landmark/><b>No financial accounts added</b><span>Add only the accounts you want Ravi OS to manage.</span></div>:accounts.map(a=><div key={a.id}><span>{a.type==='credit_card'?<CreditCard/>:<Building2/>}</span><div><b>{a.name}</b><small>{a.institution||a.type} · {a.currency}</small></div><em>{a.active?'Active':'Inactive'}</em></div>)}</div></section>}
  </main>
}
