'use client'

import Link from 'next/link'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Bell, Check, Clock3, Edit3, ListChecks, MessageCircle, Plus, RefreshCw, Trash2, X } from 'lucide-react'
import styles from './waiting-for.module.css'

type Item={id:string;title:string;person:string;notes:string;dueDate:string;dueTime:string;priority:'high'|'medium'|'low';channel:string;status:'waiting'|'done'|'cancelled';lastFollowUpAt?:string|null;completedAt?:string|null}
type Filter='waiting'|'overdue'|'done'|'all'

function todayNZ(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Pacific/Auckland',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function dueStamp(i:Item){if(!i.dueDate)return Number.MAX_SAFE_INTEGER;return new Date(`${i.dueDate}T${i.dueTime||'23:59'}:00`).getTime()}
function dueLabel(i:Item){if(!i.dueDate)return'No follow-up date';const d=new Date(`${i.dueDate}T12:00:00`);const label=d.toLocaleDateString('en-NZ',{weekday:'short',day:'numeric',month:'short'});return i.dueTime?`${label} · ${i.dueTime}`:label}

export default function WaitingForPage(){
  const[items,setItems]=useState<Item[]>([]);const[loading,setLoading]=useState(true);const[filter,setFilter]=useState<Filter>('waiting');const[open,setOpen]=useState(false);const[editing,setEditing]=useState<string|null>(null)
  const[title,setTitle]=useState('');const[person,setPerson]=useState('');const[notes,setNotes]=useState('');const[dueDate,setDueDate]=useState('');const[dueTime,setDueTime]=useState('');const[priority,setPriority]=useState<'high'|'medium'|'low'>('medium');const[channel,setChannel]=useState('');const[working,setWorking]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('')
  const load=async()=>{try{const r=await fetch('/api/waiting-for',{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();setItems(d.items||[]);setError('')}catch{setError('Waiting For could not be loaded.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const counts=useMemo(()=>{const today=todayNZ();return{waiting:items.filter(i=>i.status==='waiting').length,overdue:items.filter(i=>i.status==='waiting'&&i.dueDate&&i.dueDate<today).length,done:items.filter(i=>i.status==='done').length}},[items])
  const visible=useMemo(()=>{const today=todayNZ();return[...items].filter(i=>filter==='waiting'?i.status==='waiting':filter==='overdue'?i.status==='waiting'&&!!i.dueDate&&i.dueDate<today:filter==='done'?i.status==='done':i.status!=='cancelled').sort((a,b)=>a.status===b.status?dueStamp(a)-dueStamp(b):a.status==='waiting'?-1:1)},[items,filter])
  const reset=()=>{setEditing(null);setTitle('');setPerson('');setNotes('');setDueDate('');setDueTime('');setPriority('medium');setChannel('');setMessage('');setError('')}
  const startAdd=()=>{reset();setOpen(true)}
  const startEdit=(i:Item)=>{setEditing(i.id);setTitle(i.title);setPerson(i.person||'');setNotes(i.notes||'');setDueDate(i.dueDate||'');setDueTime(i.dueTime||'');setPriority(i.priority);setChannel(i.channel||'');setOpen(true);window.scrollTo({top:0,behavior:'smooth'})}
  async function save(e:FormEvent){e.preventDefault();if(!title.trim())return;setWorking(true);const body={title:title.trim(),person:person.trim(),notes:notes.trim(),dueDate:dueDate||null,dueTime:dueTime||null,priority,channel:channel.trim()};const r=await fetch(editing?`/api/waiting-for/${editing}`:'/api/waiting-for',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.ok){await load();setOpen(false);reset()}else setError('Could not save this item.');setWorking(false)}
  async function complete(i:Item){const r=await fetch(`/api/waiting-for/${i.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({completed:i.status!=='done'})});if(r.ok)await load()}
  async function followUp(i:Item){const r=await fetch(`/api/waiting-for/${i.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({followUp:true})});if(r.ok){setMessage(`Follow-up recorded for ${i.person||'this item'}.`);await load()}}
  async function remove(id:string){if(!confirm('Delete this Waiting For item?'))return;const r=await fetch(`/api/waiting-for/${id}`,{method:'DELETE'});if(r.ok)await load()}
  async function toTask(i:Item){const r=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:`Follow up: ${i.title}`,notes:[i.person?`Waiting on ${i.person}`:'',i.notes].filter(Boolean).join(' · '),dueDate:i.dueDate||null,dueTime:i.dueTime||null,priority:i.priority,category:'Waiting For'})});setMessage(r.ok?'Task created.':'Could not create task.')}
  async function toReminder(i:Item){if(!i.dueDate||!i.dueTime){setMessage('Add a date and time first to create a reminder.');return}const r=await fetch('/api/reminders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:`Follow up: ${i.title}`,notes:[i.person?`Waiting on ${i.person}`:'',i.notes].filter(Boolean).join(' · '),date:i.dueDate,time:i.dueTime,dueAt:new Date(`${i.dueDate}T${i.dueTime}:00`).toISOString(),source:'text'})});setMessage(r.ok?'Reminder created.':'Could not create reminder.')}

  return <main className={styles.shell}>
    <header className={styles.header}><Link href='/' className={styles.back}><ArrowLeft/>Ravi OS</Link><div><p>PERSONAL SECRETARY</p><h1>Waiting For</h1><span>Track promises, callbacks, documents, approvals and anything someone owes you.</span></div><button className={styles.add} onClick={startAdd}><Plus/>Add</button></header>
    <section className={styles.stats}><button className={filter==='waiting'?styles.active:''} onClick={()=>setFilter('waiting')}><b>{counts.waiting}</b><span>Waiting</span></button><button className={filter==='overdue'?styles.active:''} onClick={()=>setFilter('overdue')}><b>{counts.overdue}</b><span>Overdue</span></button><button className={filter==='done'?styles.active:''} onClick={()=>setFilter('done')}><b>{counts.done}</b><span>Done</span></button><button className={filter==='all'?styles.active:''} onClick={()=>setFilter('all')}><b>{items.length}</b><span>All</span></button></section>
    {message&&<div className={styles.message}>{message}</div>}
    {open&&<section className={styles.formCard}><div className={styles.formHead}><div><p>{editing?'EDIT ITEM':'NEW WAITING FOR'}</p><h2>{editing?'Update follow-up':'What are you waiting for?'}</h2></div><button onClick={()=>{setOpen(false);reset()}}><X/></button></div><form onSubmit={save}><label>What are you waiting for?<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder='e.g. Contractor to send revised quote'/></label><div className={styles.two}><label>From whom?<input value={person} onChange={e=>setPerson(e.target.value)} placeholder='Person or organisation'/></label><label>Channel<input value={channel} onChange={e=>setChannel(e.target.value)} placeholder='Email, WhatsApp, phone'/></label></div><label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder='Context, promise made, what you need back'/></label><div className={styles.two}><label>Follow up date<input type='date' value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label>Time<input type='time' value={dueTime} onChange={e=>setDueTime(e.target.value)}/></label></div><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value as 'high'|'medium'|'low')}><option value='high'>High</option><option value='medium'>Medium</option><option value='low'>Low</option></select></label>{error&&<div className={styles.error}>{error}</div>}<button className={styles.save} disabled={working||!title.trim()}>{working?'Saving…':'Save'}</button></form></section>}
    <section className={styles.listCard}>{loading?<div className={styles.empty}>Loading…</div>:visible.length===0?<div className={styles.empty}><Clock3/><b>Nothing waiting here</b><span>Add something when someone promises to get back to you.</span><button onClick={startAdd}><Plus/>Add Waiting For</button></div>:<div className={styles.list}>{visible.map(i=><article key={i.id} className={`${styles.item} ${i.status==='done'?styles.done:''}`}><button className={styles.check} onClick={()=>complete(i)} aria-label={i.status==='done'?'Reopen':'Complete'}>{i.status==='done'?<Check/>:<Clock3/>}</button><div className={styles.body}><div className={styles.titleRow}><b>{i.title}</b><em className={styles[i.priority]}>{i.priority}</em></div><small>{i.person||'No person'}{i.channel?` · ${i.channel}`:''} · {dueLabel(i)}</small>{i.notes&&<span>{i.notes}</span>}{i.lastFollowUpAt&&<em className={styles.followed}>Last followed up {new Date(i.lastFollowUpAt).toLocaleDateString('en-NZ')}</em>}</div><div className={styles.actions}><button onClick={()=>followUp(i)} title='Record follow-up'><RefreshCw/></button><button onClick={()=>toTask(i)} title='Create task'><ListChecks/></button><button onClick={()=>toReminder(i)} title='Create reminder'><Bell/></button><button onClick={()=>startEdit(i)} title='Edit'><Edit3/></button><button onClick={()=>remove(i.id)} title='Delete'><Trash2/></button></div></article>)}</div>}</section>
    <nav className={styles.bottom}><Link href='/'><span>Home</span></Link><Link href='/tasks'><ListChecks/><span>Tasks</span></Link><button className={styles.plus} onClick={startAdd}><Plus/></button><Link href='/calendar'><Clock3/><span>Calendar</span></Link></nav>
  </main>
}
