'use client'

import Link from 'next/link'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, CalendarDays, Check, Circle, Edit3, HeartHandshake, Plus, Save, Trash2, Users, X } from 'lucide-react'
import styles from './family-workspace.module.css'

type Item={id:string;title:string;notes:string;date:string;time:string;category:string;assignedTo:'ravi'|'geet'|'family';priority:'high'|'medium'|'low';status:'open'|'completed'|'cancelled';createdBy:'ravi'|'geet';updatedBy:'ravi'|'geet';completedAt?:string|null}
type Filter='upcoming'|'mine'|'completed'|'all'

function todayNZ(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Pacific/Auckland',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function stamp(i:Item){if(!i.date)return Number.MAX_SAFE_INTEGER;return new Date(`${i.date}T${i.time||'23:59'}:00`).getTime()}
function when(i:Item){if(!i.date)return'No date';const d=new Date(`${i.date}T12:00:00`).toLocaleDateString('en-NZ',{weekday:'short',day:'numeric',month:'short'});return i.time?`${d} · ${i.time}`:d}
function assignee(v:Item['assignedTo']){return v==='ravi'?'Ravi':v==='geet'?'Geet':'Family'}

export default function FamilyWorkspace({viewer}:{viewer:'ravi'|'geet'}){
  const[ready,setReady]=useState(viewer==='ravi');const[items,setItems]=useState<Item[]>([]);const[loading,setLoading]=useState(true);const[filter,setFilter]=useState<Filter>('upcoming');const[formOpen,setFormOpen]=useState(false);const[editing,setEditing]=useState<string|null>(null);const[working,setWorking]=useState(false);const[error,setError]=useState('')
  const[title,setTitle]=useState('');const[notes,setNotes]=useState('');const[date,setDate]=useState('');const[time,setTime]=useState('');const[category,setCategory]=useState('Family');const[assignedTo,setAssignedTo]=useState<'ravi'|'geet'|'family'>('family');const[priority,setPriority]=useState<'high'|'medium'|'low'>('medium')

  const load=async()=>{try{const r=await fetch('/api/family',{cache:'no-store'});if(r.status===401){if(viewer==='geet')window.location.replace('/geet');return}if(!r.ok)throw new Error();const d=await r.json();setItems(d.items||[]);setError('')}catch{setError('Family workspace is temporarily unavailable.')}finally{setLoading(false)}}
  useEffect(()=>{if(viewer==='geet'){fetch('/api/geet-auth',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(!d.authenticated)window.location.replace('/geet');else{setReady(true);load()}}).catch(()=>window.location.replace('/geet'))}else load()},[viewer])

  const counts=useMemo(()=>({open:items.filter(i=>i.status==='open').length,mine:items.filter(i=>i.status==='open'&&(i.assignedTo===viewer||i.assignedTo==='family')).length,completed:items.filter(i=>i.status==='completed').length}),[items,viewer])
  const visible=useMemo(()=>{const today=todayNZ();return [...items].filter(i=>filter==='completed'?i.status==='completed':filter==='mine'?i.status==='open'&&(i.assignedTo===viewer||i.assignedTo==='family'):filter==='upcoming'?i.status==='open'&&(!i.date||i.date>=today):i.status!=='cancelled').sort((a,b)=>a.status===b.status?stamp(a)-stamp(b):a.status==='open'?-1:1)},[items,filter,viewer])
  const reset=()=>{setEditing(null);setTitle('');setNotes('');setDate('');setTime('');setCategory('Family');setAssignedTo('family');setPriority('medium');setError('')}
  const add=()=>{reset();setFormOpen(true)}
  const edit=(i:Item)=>{setEditing(i.id);setTitle(i.title);setNotes(i.notes||'');setDate(i.date||'');setTime(i.time||'');setCategory(i.category||'Family');setAssignedTo(i.assignedTo);setPriority(i.priority);setFormOpen(true);window.scrollTo({top:0,behavior:'smooth'})}
  async function save(e:FormEvent){e.preventDefault();if(!title.trim())return;setWorking(true);const body={title:title.trim(),notes:notes.trim(),date:date||null,time:time||null,category:category.trim()||'Family',assignedTo,priority};const r=await fetch(editing?`/api/family/${editing}`:'/api/family',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.ok){await load();setFormOpen(false);reset()}else setError('Could not save this family item.');setWorking(false)}
  async function toggle(i:Item){const r=await fetch(`/api/family/${i.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({completed:i.status!=='completed'})});if(r.ok)await load()}
  async function remove(id:string){if(!confirm('Remove this family item?'))return;const r=await fetch(`/api/family/${id}`,{method:'DELETE'});if(r.ok)await load()}

  if(!ready)return <main className={styles.shell}><div className={styles.loading}>Opening family workspace…</div></main>
  const back=viewer==='geet'?'/geet':'/'
  return <main className={styles.shell}>
    <header className={styles.header}><Link href={back} className={styles.back}><ArrowLeft/>{viewer==='geet'?'Geet home':'Ravi OS'}</Link><div><p>SHARED FAMILY</p><h1>Family commitments</h1><span>Appointments, school, errands and responsibilities in one shared place.</span></div><button className={styles.add} onClick={add}><Plus/>Add</button></header>
    <section className={styles.stats}><button className={filter==='upcoming'?styles.active:''} onClick={()=>setFilter('upcoming')}><b>{counts.open}</b><span>Upcoming</span></button><button className={filter==='mine'?styles.active:''} onClick={()=>setFilter('mine')}><b>{counts.mine}</b><span>Mine + shared</span></button><button className={filter==='completed'?styles.active:''} onClick={()=>setFilter('completed')}><b>{counts.completed}</b><span>Completed</span></button><button className={filter==='all'?styles.active:''} onClick={()=>setFilter('all')}><b>{items.length}</b><span>All</span></button></section>

    {formOpen&&<section className={styles.formCard}><div className={styles.formHead}><div><p>{editing?'EDIT':'NEW FAMILY ITEM'}</p><h2>{editing?'Update commitment':'Add a family commitment'}</h2></div><button onClick={()=>{setFormOpen(false);reset()}}><X/></button></div><form onSubmit={save}><label>What is it?<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder='e.g. Parent-teacher meeting'/></label><label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder='School, doctor, address, what to bring…'/></label><div className={styles.two}><label>Date<input type='date' value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input type='time' value={time} onChange={e=>setTime(e.target.value)}/></label></div><div className={styles.two}><label>For<select value={assignedTo} onChange={e=>setAssignedTo(e.target.value as any)}><option value='family'>Family / shared</option><option value='ravi'>Ravi</option><option value='geet'>Geet</option></select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value as any)}><option value='high'>High</option><option value='medium'>Medium</option><option value='low'>Low</option></select></label></div><label>Category<input value={category} onChange={e=>setCategory(e.target.value)} placeholder='School, Health, Errand…'/></label>{error&&<div className={styles.error}>{error}</div>}<button className={styles.save} disabled={working||!title.trim()}><Save/>{working?'Saving…':'Save'}</button></form></section>}

    <section className={styles.listCard}><div className={styles.listHead}><div><p>{filter.toUpperCase()}</p><h2>{filter==='completed'?'Completed family items':filter==='mine'?`${viewer==='geet'?'Geet':'Ravi'} + shared`:'What is coming up'}</h2></div><span>{visible.length}</span></div>{loading?<div className={styles.empty}>Loading family commitments…</div>:error&&!items.length?<div className={styles.empty}>{error}</div>:visible.length===0?<div className={styles.empty}><HeartHandshake/><b>Nothing here yet</b><span>Add the next school, health or family commitment when it comes up.</span><button onClick={add}><Plus/>Add family item</button></div>:<div className={styles.list}>{visible.map(i=><article key={i.id} className={`${styles.item} ${i.status==='completed'?styles.done:''}`}><button className={styles.check} onClick={()=>toggle(i)}>{i.status==='completed'?<Check/>:<Circle/>}</button><div className={styles.body}><div className={styles.titleRow}><b>{i.title}</b><em className={styles[i.priority]}>{i.priority}</em></div><small><CalendarDays/> {when(i)} · <Users/> {assignee(i.assignedTo)} · {i.category}</small>{i.notes&&<span>{i.notes}</span>}<i>Added by {i.createdBy==='geet'?'Geet':'Ravi'}</i></div><div className={styles.actions}><button onClick={()=>edit(i)} aria-label='Edit'><Edit3/></button><button onClick={()=>remove(i.id)} aria-label='Remove'><Trash2/></button></div></article>)}</div>}</section>
  </main>
}
