'use client'

import { FormEvent,useEffect,useState } from 'react'
import { BrainCircuit,CheckCircle2,Mic,MicOff,Send,ShieldCheck,X } from 'lucide-react'

type Result={domain:string;intent:string;summary:string;confidence:number;riskLevel:string;requiresApproval:boolean;payload:any;actionId?:string;engine?:string}
export default function GlobalRaviVoice(){const[open,setOpen]=useState(false);const[listening,setListening]=useState(false);const[text,setText]=useState('');const[result,setResult]=useState<Result|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[source,setSource]=useState<'voice'|'text'>('text');const[executed,setExecuted]=useState(false);const[path,setPath]=useState('')
 useEffect(()=>setPath(window.location.pathname),[]);if(path.startsWith('/geet'))return null
 async function markExecuted(actionId?:string){if(actionId)await fetch(`/api/intelligence/actions/${actionId}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'executed'})})}
 async function autoReminder(d:Result,nextSource:'voice'|'text'){const p=d.payload||{};if(d.intent!=='create_reminder'||d.requiresApproval||!p.title||!p.date||!p.time)return false;setMessage('Setting the reminder…');const r=await fetch('/api/reminders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:p.title,notes:p.notes||'',date:p.date,time:p.time,dueAt:new Date(`${p.date}T${p.time}:00`).toISOString(),source:nextSource})});const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out.error||'Could not set the reminder');await markExecuted(d.actionId);setExecuted(true);setMessage(`Done. Reminder set for ${p.date} at ${p.time}.`);return true}
 async function interpret(input:string,nextSource:'voice'|'text'){const q=input.trim();if(!q)return;setSource(nextSource);setBusy(true);setExecuted(false);setMessage('Understanding…');setResult(null);try{const r=await fetch('/api/intelligence/interpret',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:q,source:nextSource})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not understand that');setResult(d);setMessage('');await autoReminder(d,nextSource)}catch(e){setMessage(e instanceof Error?e.message:'Could not understand that')}finally{setBusy(false)}}
 function startVoice(){const W=window as any,SR=W.SpeechRecognition||W.webkitSpeechRecognition;if(!SR){setMessage('Voice recognition is not available in this browser. Type your command below.');setOpen(true);return}const r=new SR();r.lang='en-NZ';r.interimResults=false;r.continuous=false;r.onstart=()=>{setOpen(true);setListening(true);setMessage('Listening…')};r.onend=()=>setListening(false);r.onerror=()=>{setListening(false);setMessage('I could not hear that clearly. Try again or type it.')};r.onresult=(e:any)=>{const q=String(e.results?.[0]?.[0]?.transcript||'').trim();setText(q);if(q)interpret(q,'voice')};r.start()}
 function submit(e:FormEvent){e.preventDefault();interpret(text,'text')}
 async function execute(){if(!result)return;const p=result.payload||{};let url='',body:any={};if(result.intent==='add_finance_transaction'){const amount=Number(p.amount);if(!(amount>=0)){setMessage('I need a valid amount before recording this.');return}url='/api/finance';body={kind:'transaction',type:p.type||'expense',amount,currency:String(p.currency||'NZD').toUpperCase(),baseAmountNzd:String(p.currency||'NZD').toUpperCase()==='NZD'?amount:undefined,category:p.category||'Other',merchant:p.merchant||'',date:p.date||undefined,notes:p.notes||'',source,confidence:result.confidence,riskLevel:result.riskLevel,aiActionId:result.actionId||undefined}}
 else if(result.intent==='create_task'){url='/api/tasks';body={title:p.title,notes:p.notes||'',dueDate:p.dueDate||null,dueTime:p.dueTime||null,priority:p.priority||'medium',category:p.category||'Personal'}}
 else if(result.intent==='create_reminder'){if(!p.title||!p.date||!p.time){setMessage('A reminder needs title, date and time before I can save it.');return}url='/api/reminders';body={title:p.title,notes:p.notes||'',date:p.date,time:p.time,dueAt:new Date(`${p.date}T${p.time}:00`).toISOString(),source}}
 else if(result.intent==='capture_note'){url='/api/journal';body={action:'entry_create',entryType:p.type||'note',title:p.title||'',body:p.content||result.summary,tags:Array.isArray(p.tags)?p.tags:[]}}
 else if(result.intent==='create_waiting_for'){url='/api/waiting-for';body={title:p.title,person:p.person||p.organisation||'',notes:p.organisation&&p.person?`Organisation: ${p.organisation}`:'',dueDate:p.followUpDate||null,dueTime:p.followUpTime||null,priority:p.priority||'medium',channel:p.channel||''}}
 else if(result.intent==='create_family_commitment'){url='/api/family';body={title:p.title,notes:p.notes||'',date:p.eventDate||null,time:p.eventTime||null,category:p.category||'Family',assignedTo:p.assignedTo||'family',priority:p.priority||'medium'}}
 else if(result.intent==='health_log'){url='/api/health';body={metric:{metric_date:p.date||new Date().toISOString().slice(0,10),source:'voice',sleep_hours:p.sleepHours??null,steps:p.steps??null,protein_g:p.proteinG??null,water_ml:p.waterMl??null,exercise_minutes:p.exerciseMinutes??null,weight_kg:p.weightKg??null,notes:p.notes||''}}}
 else{route();return}
 setBusy(true);setMessage('Executing the approved action…');try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Action failed');await markExecuted(result.actionId);setExecuted(true);setMessage('Done. The action was completed and recorded in the audit trail.')}catch(e){setMessage(e instanceof Error?e.message:'Action failed')}finally{setBusy(false)}}
 function route(){if(!result)return;sessionStorage.setItem('ravi-os-intelligence-draft',JSON.stringify(result));const map:Record<string,string>={finance:'/finance?ai=1',tasks:'/tasks',journal:'/journal?new=1',family:'/family',projects:'/construction',email:'/secretary',career:'/career',health:'/health',general:'/automation'};window.location.assign(map[result.domain]||'/')}
 const executable=result&&['add_finance_transaction','create_task','create_reminder','capture_note','create_waiting_for','create_family_commitment','health_log'].includes(result.intent)
 return <><button className="raviVoiceFab" aria-label="Ravi voice assistant" onClick={()=>open?setOpen(false):startVoice()}>{listening?<MicOff/>:<Mic/>}</button>{open&&<div className="raviVoiceBackdrop" onClick={()=>setOpen(false)}><section className="raviVoicePanel" onClick={e=>e.stopPropagation()}><header><span><BrainCircuit/><div><small>RAVI INTELLIGENCE</small><b>What should I manage?</b></div></span><button onClick={()=>setOpen(false)}><X/></button></header><form onSubmit={submit}><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} placeholder="Try: ‘Remind me Monday morning to call the cricket association’, ‘Spent $45 on groceries’, ‘I am waiting for John’."/><button disabled={busy||!text.trim()}><Send/>{busy?'Working…':'Understand'}</button></form>{message&&<p className="raviVoiceMessage">{message}</p>}{result&&<div className="raviVoiceResult"><div className="raviVoiceMeta"><span>{result.domain}</span><span>{Math.round((result.confidence||0)*100)}% confidence</span><span>{result.riskLevel} risk</span></div><h3>{result.summary}</h3>{executed?<p><CheckCircle2/> Completed and recorded.</p>:<p><ShieldCheck/> {result.requiresApproval?'Approval required before action.':'Safe action can be completed automatically.'}</p>}{!executed&&executable&&result.requiresApproval&&<button onClick={execute}><CheckCircle2/>Approve & execute</button>}{executed&&<button onClick={route}><CheckCircle2/>Open {result.domain==='tasks'?'Reminders / Tasks':result.domain}</button>}{!executable&&<button onClick={route}>Review in {result.domain==='email'?'Personal Secretary':result.domain.charAt(0).toUpperCase()+result.domain.slice(1)}</button>}</div>}<footer>Routine reminders can be set automatically. Email sends, money movement and other consequential actions remain explicitly gated.</footer></section></div>}</>}
