'use client'

import Link from 'next/link'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowLeftRight, Building2, CalendarClock, CircleDollarSign, FileCheck2, HardHat, IndianRupee, Landmark, NotebookPen, Pencil, PiggyBank, Plus, ReceiptIndianRupee, Save, ShieldCheck, Trash2, TrendingUp, UserRound, WalletCards, X } from 'lucide-react'
import styles from './construction.module.css'

type Project={id:string;name:string;location:string;description?:string;status:string;contract_value:number;currency:string;target_date?:string|null;target_text?:string|null;contractor_name?:string|null;contractor_phone?:string|null;contractor_email?:string|null;contractor_address?:string|null}
type Milestone={id:string;title:string;notes?:string;sequence_no:number;status:'planned'|'current'|'completed'|'blocked';due_date?:string|null;completed_at?:string|null}
type Payment={id:string;amount:number;currency:string;payment_date:string;method?:string;reference?:string;notes?:string;milestone_id?:string|null}
type DocumentRow={id:string;title:string;category:string;status:'required'|'received'|'verified'|'not_applicable';notes?:string}
type NoteRow={id:string;note:string;note_type:'note'|'risk'|'decision'|'action';created_at:string}
type LineItem={id:string;seq:number;description:string;qty:number|null;unit_rate:number|null;amount:number}
type FundRelease={id:string;release_date:string;amount_nzd:number|null;fx_rate:number|null;amount_inr:number;destination?:string;notes?:string}
type FundingContext={fxRate:{nzdToInr:number;asOf:string}|null;nroBalanceInr:number|null}
type Dashboard={project:Project;milestones:Milestone[];payments:Payment[];documents:DocumentRow[];notes:NoteRow[];lineItems:LineItem[];fundReleases:FundRelease[];context:FundingContext}
type Tab='overview'|'releases'|'payments'|'quote'|'milestones'|'documents'|'notes'

const CODE='kaptanganj-house'
const money=(n:number)=>`₹${Math.round(n||0).toLocaleString('en-IN')}`
const nzd=(n:number)=>`NZ$${Math.round(n||0).toLocaleString('en-NZ')}`
const niceDate=(d?:string|null)=>d?new Date(`${d}T12:00:00`).toLocaleDateString('en-NZ',{day:'numeric',month:'short',year:'numeric'}):'Not set'

export default function ConstructionPage(){
  const[data,setData]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[tab,setTab]=useState<Tab>('overview');const[working,setWorking]=useState(false)
  const[paymentOpen,setPaymentOpen]=useState(false);const[amount,setAmount]=useState('');const[paymentDate,setPaymentDate]=useState(new Date().toISOString().slice(0,10));const[paymentMethod,setPaymentMethod]=useState('Bank transfer');const[paymentRef,setPaymentRef]=useState('');const[paymentNotes,setPaymentNotes]=useState('');const[paymentMilestone,setPaymentMilestone]=useState('')
  const[releaseOpen,setReleaseOpen]=useState(false);const[relNzd,setRelNzd]=useState('');const[relInr,setRelInr]=useState('');const[relDate,setRelDate]=useState(new Date().toISOString().slice(0,10));const[relDest,setRelDest]=useState('HDFC NRO Savings');const[relNotes,setRelNotes]=useState('')
  const[contractorOpen,setContractorOpen]=useState(false);const[cName,setCName]=useState('');const[cPhone,setCPhone]=useState('');const[cEmail,setCEmail]=useState('');const[cAddress,setCAddress]=useState('')
  const[note,setNote]=useState('');const[noteType,setNoteType]=useState<NoteRow['note_type']>('note')
  const[milestoneOpen,setMilestoneOpen]=useState(false);const[mTitle,setMTitle]=useState('');const[mNotes,setMNotes]=useState('');const[mDue,setMDue]=useState('')

  async function load(){try{const r=await fetch(`/api/projects/${CODE}`,{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();setData(d);setError('');const p=d.project as Project;setCName(p.contractor_name||'');setCPhone(p.contractor_phone||'');setCEmail(p.contractor_email||'');setCAddress(p.contractor_address||'')}catch{setError('Project workspace could not be loaded.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  async function action(actionName:string,payload:Record<string,unknown>={}){setWorking(true);try{const r=await fetch(`/api/projects/${CODE}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:actionName,...payload})});if(!r.ok)throw new Error();await load();return true}catch{setError('That change could not be saved.');return false}finally{setWorking(false)}}

  const paid=useMemo(()=>data?.payments.reduce((s,p)=>s+Number(p.amount||0),0)||0,[data]);const total=Number(data?.project.contract_value||0);const paidPct=total?Math.min(100,Math.round(paid/total*100)):0;const completedMilestones=data?.milestones.filter(m=>m.status==='completed').length||0;const docsReady=data?.documents.filter(d=>d.status==='verified').length||0
  const totalReleased=useMemo(()=>data?.fundReleases.reduce((s,r)=>s+Number(r.amount_inr||0),0)||0,[data])
  const totalReleasedNzd=useMemo(()=>data?.fundReleases.reduce((s,r)=>s+Number(r.amount_nzd||0),0)||0,[data])
  const inHand=totalReleased-paid;const stillToRelease=Math.max(total-totalReleased,0)
  const fxRate=data?.context.fxRate?.nzdToInr||null;const stillToReleaseNzd=fxRate?stillToRelease/fxRate:null

  async function savePayment(e:FormEvent){e.preventDefault();if(!(Number(amount)>0))return;const ok=await action('payment_create',{amount:Number(amount),currency:'INR',paymentDate,method:paymentMethod,reference:paymentRef,notes:paymentNotes,milestoneId:paymentMilestone||null});if(ok){setPaymentOpen(false);setAmount('');setPaymentRef('');setPaymentNotes('');setPaymentMilestone('')}}
  async function saveRelease(e:FormEvent){e.preventDefault();if(!(Number(relInr)>0))return;const ok=await action('release_create',{amountInr:Number(relInr),amountNzd:relNzd?Number(relNzd):null,releaseDate:relDate,destination:relDest,notes:relNotes});if(ok){setReleaseOpen(false);setRelNzd('');setRelInr('');setRelNotes('')}}
  async function saveContractor(e:FormEvent){e.preventDefault();const ok=await action('project_update',{contractorName:cName,contractorPhone:cPhone,contractorEmail:cEmail,contractorAddress:cAddress});if(ok)setContractorOpen(false)}
  async function saveNote(e:FormEvent){e.preventDefault();if(!note.trim())return;const ok=await action('note_create',{note:note.trim(),noteType});if(ok){setNote('');setNoteType('note')}}
  async function addMilestone(e:FormEvent){e.preventDefault();if(!mTitle.trim())return;const seq=(data?.milestones.length||0)+1;const ok=await action('milestone_create',{title:mTitle.trim(),notes:mNotes.trim(),dueDate:mDue||null,sequenceNo:seq});if(ok){setMilestoneOpen(false);setMTitle('');setMNotes('');setMDue('')}}

  if(loading)return <main className={styles.page}><div className={styles.loading}>Opening project workspace…</div></main>
  if(!data)return <main className={styles.page}><div className={styles.loading}>{error||'Project unavailable.'}</div></main>
  const p=data.project

  return <main className={styles.page}>
    <header className={styles.header}><div><Link href='/' className={styles.back}><ArrowLeft/>Ravi OS</Link><div className={styles.title}><span><HardHat/></span><div><p>PROJECT WORKSPACE</p><h1>{p.name}</h1><small>{p.location}</small></div></div></div><span className={styles.private}><ShieldCheck/>Private</span></header>

    {error&&<div className={styles.error}>{error}</div>}
    <section className={styles.summary}>
      <div><CircleDollarSign/><span><small>Actual value</small><strong>{money(total)}</strong><em>Per quotation · {data.lineItems.length} items</em></span></div>
      <div><ArrowLeftRight/><span><small>Released from NZ</small><strong>{money(totalReleased)}</strong><em>{totalReleasedNzd>0?`${nzd(totalReleasedNzd)} sent so far`:`${data.fundReleases.length} transfer${data.fundReleases.length===1?'':'s'}`}</em></span></div>
      <div><WalletCards/><span><small>Spent</small><strong>{money(paid)}</strong><em>{paidPct}% of contract</em></span></div>
      <div><PiggyBank/><span><small>In hand (India)</small><strong>{money(inHand)}</strong><em>{inHand<0?'Spent ahead of releases':'Released, not yet spent'}</em></span></div>
      <div><TrendingUp/><span><small>Still to release</small><strong>{money(stillToRelease)}</strong><em>{stillToReleaseNzd!=null?`≈${nzd(stillToReleaseNzd)} at today's rate`:'Live rate unavailable'}</em></span></div>
      <div><CalendarClock/><span><small>Target</small><strong>{p.target_text||niceDate(p.target_date)}</strong><em>{completedMilestones}/{data.milestones.length} milestones done</em></span></div>
    </section>

    {data.context.nroBalanceInr!=null&&<div className={styles.contextBar}><Landmark/><span>HDFC NRO Savings right now: <b>{money(data.context.nroBalanceInr)}</b> — that's the whole account, not construction funds only</span></div>}

    <section className={styles.progressCard}><div><span><b>Overall payment progress</b><small>{money(paid)} of {money(total)}</small></span><strong>{paidPct}%</strong></div><div className={styles.progress}><i style={{width:`${paidPct}%`}}/></div></section>

    <nav className={styles.tabs}>{(['overview','releases','payments','quote','milestones','documents','notes'] as Tab[]).map(t=><button key={t} className={tab===t?styles.active:''} onClick={()=>setTab(t)}>{t==='overview'?'Overview':t[0].toUpperCase()+t.slice(1)}</button>)}</nav>

    {tab==='overview'&&<div className={styles.grid}>
      <section className={styles.card}><div className={styles.cardHead}><div><p>CONTRACTOR</p><h2>Primary contact</h2></div><button onClick={()=>setContractorOpen(true)}><Pencil/></button></div><div className={styles.person}><span><UserRound/></span><div><b>{p.contractor_name||'Contractor details not added'}</b><small>{p.contractor_phone||'Add mobile'}{p.contractor_email?` · ${p.contractor_email}`:''}</small>{p.contractor_address&&<em>{p.contractor_address}</em>}</div></div><div className={styles.warning}><ShieldCheck/><span><b>Before the next payment</b><small>Confirm scope, material brands, milestone evidence, defects responsibility and handover commitment in writing.</small></span></div></section>
      <section className={styles.card}><div className={styles.cardHead}><div><p>FUND RELEASES</p><h2>Money moved from NZ</h2></div><ArrowLeftRight/></div>{data.fundReleases.length===0?<div className={styles.emptySmall}>No releases recorded yet.</div>:data.fundReleases.slice(0,4).map(r=><div className={styles.paymentRow} key={r.id}><span><b>{money(r.amount_inr)}</b><small>{niceDate(r.release_date)}{r.amount_nzd?` · ${nzd(r.amount_nzd)}`:''}</small></span><em>{r.destination||'No destination noted'}</em></div>)}<button className={styles.primary} onClick={()=>setReleaseOpen(true)}><Plus/>Record release</button></section>
      <section className={styles.card}><div className={styles.cardHead}><div><p>NEXT MILESTONE</p><h2>Construction progress</h2></div><Building2/></div>{data.milestones.filter(m=>m.status!=='completed').slice(0,2).map(m=><div className={styles.nextItem} key={m.id}><span className={styles.statusDot}/><div><b>{m.title}</b><small>{m.notes}</small><em>{m.status} · {niceDate(m.due_date)}</em></div></div>)}<button className={styles.secondary} onClick={()=>setTab('milestones')}>View milestones</button></section>
      <section className={styles.card}><div className={styles.cardHead}><div><p>DOCUMENT CONTROL</p><h2>{docsReady}/{data.documents.length} verified</h2></div><FileCheck2/></div><div className={styles.miniList}>{data.documents.slice(0,5).map(d=><div key={d.id}><span className={`${styles.docState} ${styles[d.status]}`}/><b>{d.title}</b><em>{d.status.replace('_',' ')}</em></div>)}</div><button className={styles.secondary} onClick={()=>setTab('documents')}>Review documents</button></section>
      <section className={styles.card}><div className={styles.cardHead}><div><p>SPENT SO FAR</p><h2>Paid to contractor</h2></div><IndianRupee/></div>{data.payments.length===0?<div className={styles.emptySmall}>No payments recorded yet.</div>:data.payments.slice(0,4).map(x=><div className={styles.paymentRow} key={x.id}><span><b>{money(x.amount)}</b><small>{niceDate(x.payment_date)} · {x.method||'Payment'}</small></span><em>{x.reference||'No reference'}</em></div>)}<button className={styles.primary} onClick={()=>setPaymentOpen(true)}><Plus/>Record payment</button></section>
    </div>}

    {tab==='releases'&&<section className={styles.panel}><div className={styles.panelHead}><div><p>FUND RELEASE LOG</p><h2>NZD → INR, stage by stage</h2></div><button className={styles.primary} onClick={()=>setReleaseOpen(true)}><Plus/>Release</button></div>{data.fundReleases.length===0?<div className={styles.empty}><ArrowLeftRight/><b>No releases recorded</b><span>Record each transfer as you move money from NZ into the India account, so the dashboard knows what's actually landed.</span></div>:<div className={styles.ledger}>{data.fundReleases.map(r=><article key={r.id}><div><b>{money(r.amount_inr)}</b><small>{niceDate(r.release_date)}{r.amount_nzd?` · ${nzd(r.amount_nzd)}${r.fx_rate?` @ ${Number(r.fx_rate).toFixed(4)}`:''}`:''}</small>{r.notes&&<span>{r.notes}</span>}</div><em>{r.destination||'No destination noted'}</em><button onClick={()=>confirm('Delete this release record?')&&action('release_delete',{id:r.id})}><Trash2/></button></article>)}</div>}</section>}

    {tab==='payments'&&<section className={styles.panel}><div className={styles.panelHead}><div><p>PAYMENT LEDGER</p><h2>Every rupee against evidence</h2></div><button className={styles.primary} onClick={()=>setPaymentOpen(true)}><Plus/>Payment</button></div>{data.payments.length===0?<div className={styles.empty}><IndianRupee/><b>No payments recorded</b><span>Record each release against a date, method and milestone.</span></div>:<div className={styles.ledger}>{data.payments.map(x=><article key={x.id}><div><b>{money(x.amount)}</b><small>{niceDate(x.payment_date)} · {x.method||'Payment'}</small>{x.notes&&<span>{x.notes}</span>}</div><em>{x.reference||'No reference'}</em><button onClick={()=>confirm('Delete this payment record?')&&action('payment_delete',{id:x.id})}><Trash2/></button></article>)}</div>}</section>}

    {tab==='quote'&&<section className={styles.panel}><div className={styles.panelHead}><div><p>QUOTATION</p><h2>Urban Construction Company</h2></div><FileCheck2/></div><div className={styles.quoteList}>{data.lineItems.map(li=><div className={styles.quoteRow} key={li.id}><span className={styles.quoteSeq}>{li.seq}</span><div><b>{li.description}</b>{li.qty!=null&&li.unit_rate!=null&&<small>{li.qty} × ₹{Number(li.unit_rate).toLocaleString('en-IN')}</small>}</div><strong>{money(li.amount)}</strong></div>)}</div><div className={styles.quoteTotal}><span>Total estimate</span><strong>{money(total)}</strong></div></section>}

    {tab==='milestones'&&<section className={styles.panel}><div className={styles.panelHead}><div><p>MILESTONES</p><h2>Build by measurable stages</h2></div><button className={styles.primary} onClick={()=>setMilestoneOpen(true)}><Plus/>Milestone</button></div><div className={styles.milestones}>{data.milestones.map((m,i)=><article key={m.id} className={styles[m.status]}><span className={styles.number}>{String(i+1).padStart(2,'0')}</span><div><b>{m.title}</b><small>{m.notes}</small><em>{niceDate(m.due_date)}</em></div><select value={m.status} disabled={working} onChange={e=>action('milestone_update',{id:m.id,status:e.target.value})}><option value='planned'>Planned</option><option value='current'>Current</option><option value='blocked'>Blocked</option><option value='completed'>Completed</option></select></article>)}</div></section>}

    {tab==='documents'&&<section className={styles.panel}><div className={styles.panelHead}><div><p>DOCUMENTS</p><h2>Contract and evidence checklist</h2></div><FileCheck2/></div><div className={styles.documents}>{data.documents.map(d=><article key={d.id}><FileCheck2/><div><b>{d.title}</b><small>{d.category}</small></div><select value={d.status} disabled={working} onChange={e=>action('document_update',{id:d.id,status:e.target.value,notes:d.notes||''})}><option value='required'>Required</option><option value='received'>Received</option><option value='verified'>Verified</option><option value='not_applicable'>N/A</option></select></article>)}</div></section>}

    {tab==='notes'&&<section className={styles.panel}><div className={styles.panelHead}><div><p>PROJECT LOG</p><h2>Notes, risks, decisions and actions</h2></div><NotebookPen/></div><form className={styles.noteForm} onSubmit={saveNote}><select value={noteType} onChange={e=>setNoteType(e.target.value as NoteRow['note_type'])}><option value='note'>Note</option><option value='risk'>Risk</option><option value='decision'>Decision</option><option value='action'>Action</option></select><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder='e.g. Contractor must send slab photos before next payment.'/><button className={styles.primary} disabled={working||!note.trim()}><Save/>Save</button></form><div className={styles.notes}>{data.notes.length===0?<div className={styles.emptySmall}>No project log entries yet.</div>:data.notes.map(n=><article key={n.id} className={styles[n.note_type]}><div><em>{n.note_type}</em><b>{n.note}</b><small>{new Date(n.created_at).toLocaleString('en-NZ')}</small></div><button onClick={()=>action('note_delete',{id:n.id})}><Trash2/></button></article>)}</div></section>}

    {contractorOpen&&<div className={styles.modalBackdrop}><form className={styles.modal} onSubmit={saveContractor}><div className={styles.modalHead}><div><p>CONTRACTOR</p><h2>Verified contact details</h2></div><button type='button' onClick={()=>setContractorOpen(false)}><X/></button></div><label>Name<input value={cName} onChange={e=>setCName(e.target.value)}/></label><label>Mobile<input value={cPhone} onChange={e=>setCPhone(e.target.value)}/></label><label>Email<input type='email' value={cEmail} onChange={e=>setCEmail(e.target.value)}/></label><label>Address<textarea value={cAddress} onChange={e=>setCAddress(e.target.value)}/></label><button className={styles.primary} disabled={working}><Save/>Save contractor</button></form></div>}

    {paymentOpen&&<div className={styles.modalBackdrop}><form className={styles.modal} onSubmit={savePayment}><div className={styles.modalHead}><div><p>PAYMENT</p><h2>Record money paid to contractor</h2></div><button type='button' onClick={()=>setPaymentOpen(false)}><X/></button></div><div className={styles.two}><label>Amount (INR)<input type='number' min='1' value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Date<input type='date' value={paymentDate} onChange={e=>setPaymentDate(e.target.value)}/></label></div><label>Milestone<select value={paymentMilestone} onChange={e=>setPaymentMilestone(e.target.value)}><option value=''>General / not linked</option>{data.milestones.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><label>Method<input value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}/></label><label>Reference / receipt<input value={paymentRef} onChange={e=>setPaymentRef(e.target.value)}/></label><label>Notes<textarea value={paymentNotes} onChange={e=>setPaymentNotes(e.target.value)}/></label><button className={styles.primary} disabled={working||!(Number(amount)>0)}><Save/>Save payment</button></form></div>}

    {releaseOpen&&<div className={styles.modalBackdrop}><form className={styles.modal} onSubmit={saveRelease}><div className={styles.modalHead}><div><p>FUND RELEASE</p><h2>Money moved from NZ to India</h2></div><button type='button' onClick={()=>setReleaseOpen(false)}><X/></button></div><div className={styles.two}><label>Sent from NZ (NZD)<input type='number' min='0' step='0.01' value={relNzd} onChange={e=>{const v=e.target.value;setRelNzd(v);if(v&&!relInr&&fxRate)setRelInr(String(Math.round(Number(v)*fxRate)))}}/></label><label>Landed in India (INR)<input type='number' min='1' value={relInr} onChange={e=>setRelInr(e.target.value)}/></label></div>{fxRate&&<small className={styles.rateHint}>Today's rate: 1 NZD ≈ ₹{fxRate.toFixed(2)}</small>}<label>Date<input type='date' value={relDate} onChange={e=>setRelDate(e.target.value)}/></label><label>Destination<input value={relDest} onChange={e=>setRelDest(e.target.value)}/></label><label>Notes<textarea value={relNotes} onChange={e=>setRelNotes(e.target.value)}/></label><button className={styles.primary} disabled={working||!(Number(relInr)>0)}><Save/>Save release</button></form></div>}

    {milestoneOpen&&<div className={styles.modalBackdrop}><form className={styles.modal} onSubmit={addMilestone}><div className={styles.modalHead}><div><p>MILESTONE</p><h2>Add construction stage</h2></div><button type='button' onClick={()=>setMilestoneOpen(false)}><X/></button></div><label>Title<input value={mTitle} onChange={e=>setMTitle(e.target.value)}/></label><label>Due date<input type='date' value={mDue} onChange={e=>setMDue(e.target.value)}/></label><label>Acceptance / evidence required<textarea value={mNotes} onChange={e=>setMNotes(e.target.value)}/></label><button className={styles.primary} disabled={working||!mTitle.trim()}><Plus/>Add milestone</button></form></div>}
  </main>
}
