'use client'

import Link from 'next/link'
import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, BellRing, CalendarPlus, Camera, ChevronRight, Edit3, FileImage, Image as ImageIcon, Plus, Save, Trash2, X } from 'lucide-react'
import { extractPosterFields } from '../../lib/poster-extract-client'
import { readReminderCache, writeReminderCache } from '../../lib/reminder-client-cache'
import styles from './reminders.module.css'

type Reminder={id:string;title:string;notes:string;date:string;time:string;source:'text'|'voice'|'image';imageName?:string;posterUrl?:string;createdBy?:string;legacyClientId?:string;notified?:boolean}
type LegacyReminder={id:number;title:string;notes:string;date:string;time:string;source:'text'|'voice'|'image';imageName?:string;imageDataUrl?:string;notified?:boolean}
const storageKey='ravi-os-reminders-v2'
// Reminder times are usually "HH:MM" but some (bulk-imported/shared ones)
// come through as "HH:MM:SS" — naively appending ":00" to those produces
// an invalid date, which broke sorting and showed "NaNd left" countdowns.
function normTime(t:string){const m=String(t||'').match(/^(\d{1,2}):(\d{2})/);return m?`${m[1].padStart(2,'0')}:${m[2]}`:'23:59'}
function stamp(r:Reminder){return new Date(`${r.date}T${normTime(r.time)}:00`).getTime()}
function urgency(r:Reminder){const h=(stamp(r)-Date.now())/3600000;if(h<=24)return'today';if(h<=48)return'tomorrow';if(h<=72)return'soon';return'later'}
function countdown(r:Reminder){const d=stamp(r)-Date.now();if(d<0)return'Overdue';const m=Math.max(1,Math.round(d/60000));if(m<60)return`${m}m left`;const h=Math.floor(m/60);if(h<24)return`${h}h ${m%60}m left`;const days=Math.floor(h/24);return`${days}d ${h%24}h left`}
function dueAt(date:string,time:string){return new Date(`${date}T${normTime(time)}:00`).toISOString()}
function calendarUrl(r:Reminder){const start=new Date(`${r.date}T${normTime(r.time)}:00`);const end=new Date(start.getTime()+1800000);const fmt=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');const p=new URLSearchParams({action:'TEMPLATE',text:r.title,dates:`${fmt(start)}/${fmt(end)}`,details:r.notes||'Created from Ravi OS',ctz:'Pacific/Auckland'});return`https://calendar.google.com/calendar/render?${p.toString()}`}
function readLocal():Reminder[]{try{const rows:LegacyReminder[]=JSON.parse(localStorage.getItem(storageKey)||'[]');return rows.map(r=>({id:`local-${r.id}`,title:r.title,notes:r.notes||'',date:r.date,time:r.time,source:r.source,imageName:r.imageName,posterUrl:r.imageDataUrl,createdBy:'ravi',legacyClientId:String(r.id),notified:r.notified}))}catch{return[]}}
function writeLocal(rows:LegacyReminder[]){localStorage.setItem(storageKey,JSON.stringify(rows))}
function mergeReminders(server:Reminder[],local:Reminder[]){const serverLegacy=new Set(server.map(r=>r.legacyClientId).filter(Boolean));return [...server,...local.filter(r=>!r.legacyClientId||!serverLegacy.has(r.legacyClientId))].sort((a,b)=>stamp(a)-stamp(b))}

export default function ReminderCentre(){
  const[reminders,setReminders]=useState<Reminder[]>([]);const[loading,setLoading]=useState(true);const[formOpen,setFormOpen]=useState(false);const[editing,setEditing]=useState<string|null>(null)
  const[title,setTitle]=useState('');const[date,setDate]=useState('');const[time,setTime]=useState('');const[venue,setVenue]=useState('');const[imageName,setImageName]=useState('');const[imageData,setImageData]=useState('')
  const[working,setWorking]=useState(false);const[message,setMessage]=useState('');const[notificationStatus,setNotificationStatus]=useState('Not enabled');const[syncMessage,setSyncMessage]=useState('')

  const load=async()=>{const local=readLocal();const cached=readReminderCache<Reminder>();const instant=mergeReminders(cached,local);if(instant.length){setReminders(instant);setLoading(false)}else if(local.length){setReminders(local);setLoading(false)}try{const r=await fetch('/api/reminders');if(r.ok){const d=await r.json();const server=d.reminders||[];writeReminderCache(server);setReminders(mergeReminders(server,local));setSyncMessage('')}else if(instant.length){setSyncMessage('Showing the latest saved reminder snapshot while shared sync reconnects.')}}catch{if(instant.length)setSyncMessage('Showing the latest saved reminder snapshot while shared sync reconnects.')}finally{setLoading(false)}}
  const migrateLocal=async()=>{const local=readLocal();if(!local.length)return;let allSaved=true;for(const old of local){try{const r=await fetch('/api/reminders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:old.title,notes:old.notes||'',date:old.date,time:old.time,dueAt:dueAt(old.date,old.time),source:old.source,imageName:old.imageName,imageDataUrl:old.posterUrl,legacyClientId:old.legacyClientId})});if(!r.ok)allSaved=false}catch{allSaved=false}}if(allSaved)localStorage.setItem('ravi-os-reminders-migrated','1')}
  useEffect(()=>{if('Notification'in window)setNotificationStatus(Notification.permission==='granted'?'Enabled on this device':'Not enabled');const cached=readReminderCache<Reminder>();const local=readLocal();const instant=mergeReminders(cached,local);if(instant.length){setReminders(instant);setLoading(false)};(async()=>{await migrateLocal();await load()})()},[])
  const sorted=useMemo(()=>[...reminders].sort((a,b)=>stamp(a)-stamp(b)),[reminders]);const upcoming=useMemo(()=>sorted.filter(r=>stamp(r)>=Date.now()),[sorted])
  const reset=()=>{setEditing(null);setTitle('');setDate('');setTime('');setVenue('');setImageName('');setImageData('');setMessage('')}
  const openAdd=()=>{reset();setFormOpen(true)}
  const edit=(r:Reminder)=>{setEditing(r.id);setTitle(r.title);setDate(r.date);setTime(r.time);setVenue(r.notes||'');setImageName(r.imageName||'');setImageData(r.posterUrl||'');setFormOpen(true);window.scrollTo({top:0,behavior:'smooth'})}
  const requestNotifications=async()=>{if(!('Notification'in window)){setNotificationStatus('Use Calendar alerts on this browser');return}const p=await Notification.requestPermission();setNotificationStatus(p==='granted'?'Enabled on this device':'Not enabled')}
  async function onPoster(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setWorking(true);setMessage('Reading the event poster…');setImageName(file.name);setTitle('');setDate('');setTime('');setVenue('');try{const p=await extractPosterFields(file);setImageData(p.imageDataUrl);setTitle(p.title==='Event reminder'?'':p.title);setDate(p.date||'');setTime(p.time||'');setVenue([p.venue,p.address].filter(Boolean).join(', '));setMessage(p.title&&p.title!=='Event reminder'&&p.date&&p.time?'Poster read. Check once and save.':'I could not confidently read every field. Please fill only the missing field(s), then save.')}catch{setImageData('');setMessage('I could not read this poster reliably. Please enter the event title, date, time and venue.')}finally{setWorking(false)}}
  async function save(){if(!title.trim()||!date||!time)return;setWorking(true);setMessage('Saving…');const isLocalEdit=Boolean(editing?.startsWith('local-'));let legacyId=editing?.startsWith('local-')?Number(editing.slice(6)):Date.now();let legacyRows:LegacyReminder[]=[];try{legacyRows=JSON.parse(localStorage.getItem(storageKey)||'[]')}catch{};const localRow:LegacyReminder={id:legacyId,title:title.trim(),notes:venue.trim(),date,time,source:imageName?'image':'text',imageName:imageName||undefined,imageDataUrl:imageData||undefined};if(isLocalEdit)legacyRows=legacyRows.map(r=>r.id===legacyId?localRow:r);else if(!editing)legacyRows=[localRow,...legacyRows];writeLocal(legacyRows);setReminders(prev=>mergeReminders(prev.filter(r=>r.id!==`local-${legacyId}`),readLocal()));const body={title:title.trim(),notes:venue.trim(),date,time,dueAt:dueAt(date,time),source:imageName?'image':'text',imageName:imageName||undefined,imageDataUrl:imageData||undefined,legacyClientId:String(legacyId)};try{const r=await fetch(editing&&!isLocalEdit?`/api/reminders/${editing}`:'/api/reminders',{method:editing&&!isLocalEdit?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.ok){await load();setSyncMessage('')}else setSyncMessage('Saved safely on this device. Shared sync is not connected yet.')}catch{setSyncMessage('Saved safely on this device. Shared sync is not connected yet.')}setFormOpen(false);reset();setWorking(false)}
  async function remove(id:string){if(!confirm('Delete this reminder?'))return;if(id.startsWith('local-')){const localId=Number(id.slice(6));let rows:LegacyReminder[]=[];try{rows=JSON.parse(localStorage.getItem(storageKey)||'[]')}catch{};writeLocal(rows.filter(r=>r.id!==localId));setReminders(prev=>prev.filter(r=>r.id!==id));return}const r=await fetch(`/api/reminders/${id}`,{method:'DELETE'});if(r.ok)await load()}
  return <main className={styles.shell}>
    <header className={styles.header}><Link href="/" className={styles.back}><ArrowLeft/> Ravi OS</Link><div className={styles.heading}><p>REMINDERS</p><h1>What’s coming up?</h1><span>One shared reminder list for Ravi and Geet. Nearest event always comes first.</span></div><button onClick={requestNotifications} className={styles.notify}><BellRing/><span><b>Phone alerts</b><small>{notificationStatus}</small></span></button></header>
    {syncMessage&&<div className={styles.saved} style={{maxWidth:1180,margin:'0 auto 12px'}}>{syncMessage}</div>}
    <section className={styles.captureGrid}><div className={styles.captureCard}><div className={styles.captureHead}><span><Plus/></span><div><p>ADD REMINDER</p><h2>Poster or quick entry</h2></div></div><div className={styles.captureActions}><label><ImageIcon/>Choose poster<input type="file" accept="image/*" onChange={e=>{openAdd();onPoster(e)}}/></label><label><Camera/>Use camera<input type="file" accept="image/*" capture="environment" onChange={e=>{openAdd();onPoster(e)}}/></label><button className={styles.analyse} onClick={openAdd}><Plus/>Type reminder</button></div><p style={{fontSize:11,color:'#748078',margin:'12px 0 0'}}>Poster extraction keeps only event title, date, time, venue and address.</p></div><div className={styles.confirmCard}><div className={styles.confirmHead}><div><p>NEXT</p><h2>{upcoming[0]?.title||'No upcoming reminder'}</h2></div><span>{upcoming[0]?countdown(upcoming[0]):'All clear'}</span></div>{upcoming[0]?<><div className={styles.two}><div><small>Date</small><b>{new Date(`${upcoming[0].date}T12:00:00`).toLocaleDateString('en-NZ',{day:'numeric',month:'long',year:'numeric'})}</b></div><div><small>Time</small><b>{upcoming[0].time}</b></div></div>{upcoming[0].notes&&<p style={{fontSize:11,color:'#52645b'}}>{upcoming[0].notes}</p>}<Link href={`/reminders/${upcoming[0].id}`} className={styles.create}>Open reminder</Link></>:<button className={styles.create} onClick={openAdd}><Plus/>Add first reminder</button>}</div></section>
    {formOpen&&<section className={styles.confirmCard} style={{maxWidth:1180,margin:'14px auto'}}><div className={styles.confirmHead}><div><p>{editing?'EDIT':'NEW REMINDER'}</p><h2>{editing?'Update reminder':'Check and save'}</h2></div><button onClick={()=>{setFormOpen(false);reset()}} aria-label="Close"><X/></button></div>{imageData&&<div className={styles.previewWrap}><img src={imageData} alt="Selected poster"/><div><FileImage/><span><b>{imageName}</b><small>{message}</small></span></div></div>}{!imageData&&message&&<div className={styles.saved}>{message}</div>}<label>Event title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Event title"/></label><div className={styles.two}><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div><label>Venue & address<input value={venue} onChange={e=>setVenue(e.target.value)} placeholder="Venue name and address"/></label><button className={styles.create} disabled={working||!title.trim()||!date||!time} onClick={save}><Save/>{working?'Working…':editing?'Save changes':'Save reminder'}</button></section>}
    <section className={styles.listCard}><div className={styles.listHead}><div><p>UPCOMING</p><h2>Your shared reminders</h2></div><span>{upcoming.length} upcoming</span></div>{loading?<div className={styles.empty}><BellRing/><b>Loading reminders…</b></div>:sorted.length===0?<div className={styles.empty}><BellRing/><b>No reminders yet</b><span>Add one from a poster or type it in.</span></div>:<div className={styles.list}>{sorted.map(r=><article key={r.id} className={styles[urgency(r)]}><Link href={r.id.startsWith('local-')?'/reminders':`/reminders/${r.id}`} className={styles.reminderLink}>{r.posterUrl?<img src={r.posterUrl} className={styles.thumb} alt="Reminder poster"/>:<div className={styles.dateBox}><b>{new Date(`${r.date}T12:00:00`).toLocaleDateString('en-NZ',{day:'2-digit',month:'short'})}</b><span>{r.time}</span></div>}<div className={styles.reminderText}><b>{r.title}</b><small>{r.notes||`Added by ${r.createdBy==='geet'?'Geet':'Ravi'}`}</small><span>{countdown(r)}</span></div><ChevronRight className={styles.chevron}/></Link><div className={styles.rowActions}><a href={calendarUrl(r)} target="_blank" rel="noreferrer"><CalendarPlus/>Calendar</a><button onClick={()=>edit(r)} aria-label="Edit reminder"><Edit3/></button><button onClick={()=>remove(r.id)} aria-label="Delete reminder"><Trash2/></button></div></article>)}</div>}</section>
  </main>
}