'use client'

import Link from 'next/link'
import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, BellRing, CalendarPlus, Camera, ChevronRight, Edit3, FileImage, Image as ImageIcon, Plus, Save, Trash2, X } from 'lucide-react'
import { parsePosterSemantics } from '../../lib/reminder-poster-parser'
import { readPosterText } from '../../lib/poster-ocr-client'
import styles from './reminders.module.css'

type Reminder={id:string;title:string;notes:string;date:string;time:string;source:'text'|'voice'|'image';imageName?:string;posterUrl?:string;createdBy?:string;legacyClientId?:string;notified?:boolean}
type LegacyReminder={id:number;title:string;notes:string;date:string;time:string;source:'text'|'voice'|'image';imageName?:string;imageDataUrl?:string}
const storageKey='ravi-os-reminders-v2'
function stamp(r:Reminder){return new Date(`${r.date}T${r.time||'23:59'}:00`).getTime()}
function urgency(r:Reminder){const h=(stamp(r)-Date.now())/3600000;if(h<=24)return'today';if(h<=48)return'tomorrow';if(h<=72)return'soon';return'later'}
function countdown(r:Reminder){const d=stamp(r)-Date.now();if(d<0)return'Overdue';const m=Math.max(1,Math.round(d/60000));if(m<60)return`${m}m left`;const h=Math.floor(m/60);if(h<24)return`${h}h ${m%60}m left`;const days=Math.floor(h/24);return`${days}d ${h%24}h left`}
function dueAt(date:string,time:string){return new Date(`${date}T${time}:00`).toISOString()}
function calendarUrl(r:Reminder){const start=new Date(`${r.date}T${r.time}:00`);const end=new Date(start.getTime()+1800000);const fmt=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');const p=new URLSearchParams({action:'TEMPLATE',text:r.title,dates:`${fmt(start)}/${fmt(end)}`,details:r.notes||'Created from Ravi OS',ctz:'Pacific/Auckland'});return`https://calendar.google.com/calendar/render?${p.toString()}`}
function posterPreview(file:File):Promise<string>{return new Promise(resolve=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result||''));fr.onerror=()=>resolve('');fr.readAsDataURL(file)})}

export default function ReminderCentre(){
  const[reminders,setReminders]=useState<Reminder[]>([]);const[loading,setLoading]=useState(true);const[formOpen,setFormOpen]=useState(false);const[editing,setEditing]=useState<string|null>(null)
  const[title,setTitle]=useState('');const[date,setDate]=useState('');const[time,setTime]=useState('');const[venue,setVenue]=useState('');const[imageName,setImageName]=useState('');const[imageData,setImageData]=useState('')
  const[working,setWorking]=useState(false);const[message,setMessage]=useState('');const[notificationStatus,setNotificationStatus]=useState('Not enabled')

  const load=async()=>{const r=await fetch('/api/reminders',{cache:'no-store'});if(r.ok){const d=await r.json();setReminders(d.reminders||[])}setLoading(false)}
  const migrateLocal=async()=>{let legacy:LegacyReminder[]=[];try{legacy=JSON.parse(localStorage.getItem(storageKey)||'[]')}catch{};if(!legacy.length)return;const current=await fetch('/api/reminders',{cache:'no-store'});if(!current.ok)return;const d=await current.json();const existing=new Set((d.reminders||[]).map((x:Reminder)=>x.legacyClientId).filter(Boolean));for(const old of legacy){const legacyClientId=String(old.id);if(existing.has(legacyClientId))continue;await fetch('/api/reminders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:old.title,notes:old.notes||'',date:old.date,time:old.time,dueAt:dueAt(old.date,old.time),source:old.source,imageName:old.imageName,imageDataUrl:old.imageDataUrl,legacyClientId})})}localStorage.setItem('ravi-os-reminders-migrated','1')}
  useEffect(()=>{if('Notification'in window)setNotificationStatus(Notification.permission==='granted'?'Enabled on this device':'Not enabled');(async()=>{await migrateLocal();await load()})()},[])
  const sorted=useMemo(()=>[...reminders].sort((a,b)=>stamp(a)-stamp(b)),[reminders]);const upcoming=useMemo(()=>sorted.filter(r=>stamp(r)>=Date.now()),[sorted])
  const reset=()=>{setEditing(null);setTitle('');setDate('');setTime('');setVenue('');setImageName('');setImageData('');setMessage('')}
  const openAdd=()=>{reset();setFormOpen(true)}
  const edit=(r:Reminder)=>{setEditing(r.id);setTitle(r.title);setDate(r.date);setTime(r.time);setVenue(r.notes||'');setImageName(r.imageName||'');setImageData('');setFormOpen(true);window.scrollTo({top:0,behavior:'smooth'})}
  const requestNotifications=async()=>{if(!('Notification'in window)){setNotificationStatus('Use Calendar alerts on this browser');return}const p=await Notification.requestPermission();setNotificationStatus(p==='granted'?'Enabled on this device':'Permission not granted')}

  async function onPoster(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setWorking(true);setMessage('Reading event title, date, time and venue…');setImageName(file.name);setImageData(await posterPreview(file));setTitle('');setDate('');setTime('');setVenue('');try{const text=await readPosterText(file);const p=parsePosterSemantics(text);setTitle(p.title==='Event reminder'?'':p.title);setDate(p.date||'');setTime(p.time||'');setVenue([p.venue,p.address].filter(Boolean).join(', '));setMessage(p.title==='Event reminder'||!p.date||!p.time?'I could not confidently read every field. Please check the blanks before saving.':'Poster read. Check the five fields once, then save.')}catch{setMessage('I could not read this poster reliably. Please enter the five fields manually.')}finally{setWorking(false)}}
  async function save(){if(!title.trim()||!date||!time)return;setWorking(true);setMessage('Saving…');const body={title:title.trim(),notes:venue.trim(),date,time,dueAt:dueAt(date,time),source:imageName?'image':'text',imageName:imageName||undefined,imageDataUrl:imageData||undefined};const r=await fetch(editing?`/api/reminders/${editing}`:'/api/reminders',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.ok){await load();setFormOpen(false);reset()}else setMessage('Could not save reminder. Please try again.');setWorking(false)}
  async function remove(id:string){if(!confirm('Delete this reminder?'))return;const r=await fetch(`/api/reminders/${id}`,{method:'DELETE'});if(r.ok)await load()}

  return <main className={styles.shell}>
    <header className={styles.header}><Link href="/" className={styles.back}><ArrowLeft/> Ravi OS</Link><div className={styles.heading}><p>REMINDERS</p><h1>What’s coming up?</h1><span>One shared reminder list for Ravi and Geet. Nearest event always comes first.</span></div><button onClick={requestNotifications} className={styles.notify}><BellRing/><span><b>Phone alerts</b><small>{notificationStatus}</small></span></button></header>
    <section className={styles.captureGrid}><div className={styles.captureCard}><div className={styles.captureHead}><span><Plus/></span><div><p>ADD REMINDER</p><h2>Poster or quick entry</h2></div></div><div className={styles.captureActions}><label><ImageIcon/>Choose poster<input type="file" accept="image/*" onChange={e=>{openAdd();onPoster(e)}}/></label><label><Camera/>Use camera<input type="file" accept="image/*" capture="environment" onChange={e=>{openAdd();onPoster(e)}}/></label><button className={styles.analyse} onClick={openAdd}><Plus/>Type reminder</button></div><p style={{fontSize:11,color:'#748078',margin:'12px 0 0'}}>Poster extraction keeps only event title, date, time, venue and address.</p></div><div className={styles.confirmCard}><div className={styles.confirmHead}><div><p>NEXT</p><h2>{upcoming[0]?.title||'No upcoming reminder'}</h2></div><span>{upcoming[0]?countdown(upcoming[0]):'All clear'}</span></div>{upcoming[0]?<><div className={styles.two}><div><small>Date</small><b>{new Date(`${upcoming[0].date}T12:00:00`).toLocaleDateString('en-NZ',{day:'numeric',month:'long',year:'numeric'})}</b></div><div><small>Time</small><b>{upcoming[0].time}</b></div></div>{upcoming[0].notes&&<p style={{fontSize:11,color:'#52645b'}}>{upcoming[0].notes}</p>}<Link href={`/reminders/${upcoming[0].id}`} className={styles.create}>Open reminder</Link></>:<button className={styles.create} onClick={openAdd}><Plus/>Add first reminder</button>}</div></section>
    {formOpen&&<section className={styles.confirmCard} style={{maxWidth:1180,margin:'14px auto'}}><div className={styles.confirmHead}><div><p>{editing?'EDIT':'NEW REMINDER'}</p><h2>{editing?'Update reminder':'Check and save'}</h2></div><button onClick={()=>{setFormOpen(false);reset()}} aria-label="Close"><X/></button></div>{imageData&&<div className={styles.previewWrap}><img src={imageData} alt="Selected poster"/><div><FileImage/><span><b>{imageName}</b><small>{message}</small></span></div></div>}{!imageData&&message&&<div className={styles.saved}>{message}</div>}<label>Event title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Event title"/></label><div className={styles.two}><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div><label>Venue & address<input value={venue} onChange={e=>setVenue(e.target.value)} placeholder="Venue name and address"/></label><button className={styles.create} disabled={working||!title.trim()||!date||!time} onClick={save}><Save/>{working?'Working…':editing?'Save changes':'Save reminder'}</button></section>}
    <section className={styles.listCard}><div className={styles.listHead}><div><p>UPCOMING</p><h2>Your shared reminders</h2></div><span>{upcoming.length} upcoming</span></div>{loading?<div className={styles.empty}><BellRing/><b>Loading reminders…</b></div>:sorted.length===0?<div className={styles.empty}><BellRing/><b>No reminders yet</b><span>Add one from a poster or type it in.</span></div>:<div className={styles.list}>{sorted.map(r=><article key={r.id} className={styles[urgency(r)]}><Link href={`/reminders/${r.id}`} className={styles.reminderLink}>{r.posterUrl?<img src={r.posterUrl} className={styles.thumb} alt="Reminder poster"/>:<div className={styles.dateBox}><b>{new Date(`${r.date}T12:00:00`).toLocaleDateString('en-NZ',{day:'2-digit',month:'short'})}</b><span>{r.time}</span></div>}<div className={styles.reminderText}><b>{r.title}</b><small>{r.notes||`Added by ${r.createdBy==='geet'?'Geet':'Ravi'}`}</small><span>{countdown(r)}</span></div><ChevronRight className={styles.chevron}/></Link><div className={styles.rowActions}><a href={calendarUrl(r)} target="_blank" rel="noreferrer"><CalendarPlus/>Calendar</a><button onClick={()=>edit(r)} aria-label="Edit reminder"><Edit3/></button><button onClick={()=>remove(r.id)} aria-label="Delete reminder"><Trash2/></button></div></article>)}</div>}</section>
  </main>
}
