import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const s=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}});const B="ravi-os-reminder-images";const H={"Content-Type":"application/json","Cache-Control":"no-store"};const rep=(d:unknown,st=200)=>new Response(JSON.stringify(d),{status:st,headers:H});
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function token(){const b=new Uint8Array(32);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,"0")).join("")}
// Repeating reminders: event_date/event_time are Auckland wall-clock values.
// Once a repeating reminder's day has passed in Auckland, list() moves it on
// to its next date, counted from recurrence_start so monthly reminders on the
// 29th-31st don't drift after a short month.
const TZ='Pacific/Auckland',REP=['daily','weekly','fortnightly','monthly','yearly'];
const ymd=(ms:number)=>new Date(ms).toISOString().slice(0,10);
function todayNZ(){return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function tzOffset(ms:number){const p:Record<string,number>={};for(const x of new Intl.DateTimeFormat('en-US',{timeZone:TZ,hourCycle:'h23',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).formatToParts(new Date(ms)))if(x.type!=='literal')p[x.type]=Number(x.value);return Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second)-ms}
function nzToUtc(date:string,time:string){const [y,mo,d]=date.split('-').map(Number),[h,mi]=time.split(':').map(Number);const guess=Date.UTC(y,mo-1,d,h,mi);let t=guess-tzOffset(guess);const o2=tzOffset(t);if(guess-o2!==t)t=guess-o2;return new Date(t).toISOString()}
function nextDate(start:string,pattern:string,today:string){if(start>=today)return start;const [y,m,d]=start.split('-').map(Number);if(pattern==='daily')return today;if(pattern==='weekly'||pattern==='fortnightly'){const step=pattern==='weekly'?7:14,diff=Math.round((Date.parse(today)-Date.parse(start))/864e5);return ymd(Date.UTC(y,m-1,d+Math.ceil(diff/step)*step))}if(pattern==='monthly'||pattern==='yearly'){const step=pattern==='monthly'?1:12;for(let n=step;n<=2400;n+=step){const mm=m-1+n,yy=y+Math.floor(mm/12),mo=mm%12,last=new Date(Date.UTC(yy,mo+1,0)).getUTCDate(),c=ymd(Date.UTC(yy,mo,Math.min(d,last)));if(c>=today)return c}}return null}
async function roll(){const today=todayNZ();const {data}=await s.from('ravi_os_reminders').select('id,event_date,event_time,recurrence_pattern,recurrence_end_date,recurrence_start').eq('status','active').in('recurrence_pattern',REP).lt('event_date',today);for(const r of data||[]){const next=nextDate(String(r.recurrence_start||r.event_date),String(r.recurrence_pattern),today);if(!next||(r.recurrence_end_date&&next>r.recurrence_end_date))continue;const t=r.event_time?String(r.event_time).slice(0,5):'09:00';await s.from('ravi_os_reminders').update({event_date:next,due_at:nzToUtc(next,t),updated_at:new Date().toISOString()}).eq('id',r.id).eq('event_date',r.event_date)}}
function repeatFields(b:any){const v=String(b.repeat||'none'),pattern=REP.includes(v)?v:null,until=String(b.repeatUntil||'');return{recurrence_pattern:pattern,recurrence_end_date:pattern&&/^\d{4}-\d{2}-\d{2}$/.test(until)?until:null}}
async function login(actor:string,pin:string){if(!['ravi','geet'].includes(actor)||!pin)return rep({error:'Invalid credentials'},401);const {data}=await s.from('ravi_os_family_access').select('actor,pin_hash,enabled').eq('actor',actor).maybeSingle();if(!data||!data.enabled||data.pin_hash!==await sha(pin))return rep({error:'Invalid credentials'},401);const t=token(),expiresAt=new Date(Date.now()+30*864e5).toISOString();await s.from('ravi_os_family_sessions').delete().lt('expires_at',new Date().toISOString());const x=await s.from('ravi_os_family_sessions').insert({token_hash:await sha(t),actor,expires_at:expiresAt});return x.error?rep({error:'Unable to create family session'},500):rep({token:t,actor,expiresAt})}
async function actor(req:Request){const t=req.headers.get('x-family-session')||'';if(!t)return null;const {data}=await s.from('ravi_os_family_sessions').select('actor,expires_at').eq('token_hash',await sha(t)).maybeSingle();return data&&new Date(data.expires_at).getTime()>Date.now()?data.actor:null}
async function signed(path:string|null){if(!path)return undefined;const {data}=await s.storage.from(B).createSignedUrl(path,86400);return data?.signedUrl||undefined}
async function list(){try{await roll()}catch(e){console.error('roll failed',e)}const now=new Date().toISOString();const [{data:r,error},{data:a}]=await Promise.all([s.from('ravi_os_reminders').select('id,title,notes,due_at,event_date,event_time,timezone,source,status,legacy_client_id,created_by,updated_by,created_at,recurrence_pattern,recurrence_end_date').eq('status','active').order('due_at',{ascending:true}),s.from('ravi_os_reminder_attachments').select('id,reminder_id,original_filename,object_path,expires_at').gt('expires_at',now).order('created_at',{ascending:false})]);if(error)throw error;const m=new Map<string,any>();for(const x of a||[])if(!m.has(x.reminder_id))m.set(x.reminder_id,x);const paths=[...m.values()].map(x=>x.object_path).filter(Boolean);const urls=new Map<string,string>();if(paths.length){const {data}=await s.storage.from(B).createSignedUrls(paths,86400);(data||[]).forEach((x:any,i:number)=>{if(x?.signedUrl)urls.set(paths[i],x.signedUrl)})}return (r||[]).map(x=>{const at=m.get(x.id);return{id:x.id,title:x.title,notes:x.notes||'',date:x.event_date||String(x.due_at).slice(0,10),time:x.event_time?String(x.event_time).slice(0,5):'',source:x.source,imageName:at?.original_filename||undefined,posterUrl:at?urls.get(at.object_path):undefined,createdBy:x.created_by||'ravi',updatedBy:x.updated_by||'ravi',legacyClientId:x.legacy_client_id||undefined,repeat:x.recurrence_pattern||'none',repeatUntil:x.recurrence_end_date||undefined}})}
function image(v:unknown){if(typeof v!=='string')return null;const m=v.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/);if(!m)return null;try{const z=atob(m[2]);return{mime:m[1],bytes:Uint8Array.from(z,c=>c.charCodeAt(0))}}catch{return null}}
async function create(a:'ravi'|'geet',b:any){const title=String(b.title||'').trim(),date=String(b.date||''),time=String(b.time||'');if(!title||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(time))return rep({error:'Title, date and time are required'},400);const legacy=b.legacyClientId?String(b.legacyClientId):null;if(legacy){const {data}=await s.from('ravi_os_reminders').select('id').eq('legacy_client_id',legacy).maybeSingle();if(data?.id)return rep({id:data.id,duplicate:true})}const id=crypto.randomUUID(),due=String(b.dueAt||nzToUtc(date,time));const q=await s.from('ravi_os_reminders').insert({id,title,notes:String(b.notes||''),due_at:due,event_date:date,event_time:time,timezone:'Pacific/Auckland',source:['text','voice','image'].includes(b.source)?b.source:'text',status:'active',legacy_client_id:legacy,created_by:a,updated_by:a,...repeatFields(b),recurrence_start:date});if(q.error)return rep({error:q.error.message},500);const im=image(b.imageDataUrl);if(im&&im.bytes.length<=10*1024*1024){const ext=im.mime.includes('png')?'png':im.mime.includes('webp')?'webp':'jpg',path=`shared/${id}/${crypto.randomUUID()}.${ext}`,u=await s.storage.from(B).upload(path,im.bytes,{contentType:im.mime,upsert:false});if(!u.error)await s.from('ravi_os_reminder_attachments').insert({reminder_id:id,bucket_id:B,object_path:path,original_filename:String(b.imageName||`poster.${ext}`),mime_type:im.mime,size_bytes:im.bytes.length,expires_at:new Date(Date.now()+90*864e5).toISOString()})}return rep({id})}
async function update(a:'ravi'|'geet',b:any){const id=String(b.id||''),title=String(b.title||'').trim(),date=String(b.date||''),time=String(b.time||'');if(!id||!title||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(time))return rep({error:'Invalid reminder'},400);const q=await s.from('ravi_os_reminders').update({title,notes:String(b.notes||''),due_at:String(b.dueAt||nzToUtc(date,time)),event_date:date,event_time:time,...('repeat' in b?repeatFields(b):{}),recurrence_start:date,updated_by:a,updated_at:new Date().toISOString()}).eq('id',id);return q.error?rep({error:q.error.message},500):rep({ok:true})}
async function del(b:any){const id=String(b.id||'');if(!id)return rep({error:'Missing id'},400);const {data}=await s.from('ravi_os_reminder_attachments').select('object_path').eq('reminder_id',id);const p=(data||[]).map(x=>x.object_path).filter(Boolean);if(p.length)await s.storage.from(B).remove(p);await s.from('ravi_os_reminder_attachments').delete().eq('reminder_id',id);const q=await s.from('ravi_os_reminders').delete().eq('id',id);return q.error?rep({error:q.error.message},500):rep({ok:true})}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response(null,{status:204});if(req.method!=='POST')return rep({error:'POST only'},405);let b:any={};try{b=await req.json()}catch{return rep({error:'Invalid JSON'},400)}const ac=String(b.action||'');if(ac==='login')return login(String(b.actor||''),String(b.pin||''));const who=await actor(req);if(!who)return rep({error:'Family session expired'},401);try{if(ac==='logout'){const t=req.headers.get('x-family-session')||'';if(t)await s.from('ravi_os_family_sessions').delete().eq('token_hash',await sha(t));return rep({ok:true})}if(ac==='list')return rep({reminders:await list()});if(ac==='create')return create(who,b);if(ac==='update')return update(who,b);if(ac==='delete')return del(b);if(ac==='get'){const rows=await list(),r=rows.find((x:any)=>x.id===String(b.id||''));return r?rep({reminder:r}):rep({error:'Not found'},404)}return rep({error:'Unknown action'},400)}catch(e){return rep({error:e instanceof Error?e.message:'Unexpected error'},500)}});
